# syntax=docker/dockerfile:1

# Use the official Bun image
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# Copy everything needed for the docs
COPY packages/docs/ ./
COPY packages/core/ /usr/src/core/
COPY .git/ ./.git/
COPY tsconfig.json ./

# Install dependencies and build
RUN bun install && \
    bun run build

# Run the server
USER bun
EXPOSE 3000/tcp
CMD ["bun", "run", "build"]