export const getAuthModuleParamsSimiles = [
    "VIEW_AUTH_PARAMS",
    "GET_AUTH_PARAMS",
    "CHECK_AUTH_PARAMS",
    "FETCH_AUTH_PARAMS",
    "READ_AUTH_PARAMS",
    "DISPLAY_AUTH_PARAMS",
    "SHOW_AUTH_PARAMS",
    "LIST_AUTH_PARAMS",
    "RETRIEVE_AUTH_PARAMS",
];

export const getAccountDetailsSimiles = [
    "VIEW_AUTH_ACCOUNT",
    "GET_AUTH_ACCOUNT",
    "CHECK_AUTH_ACCOUNT",
    "FETCH_AUTH_ACCOUNT",
    "READ_AUTH_ACCOUNT",
    "DISPLAY_AUTH_ACCOUNT",
    "SHOW_AUTH_ACCOUNT",
    "LIST_AUTH_ACCOUNT",
    "RETRIEVE_AUTH_ACCOUNT",
];

export const getAccountsSimiles = [
    "VIEW_AUTH_ACCOUNTS",
    "GET_AUTH_ACCOUNTS",
    "CHECK_AUTH_ACCOUNTS",
    "FETCH_AUTH_ACCOUNTS",
    "READ_AUTH_ACCOUNTS",
    "DISPLAY_AUTH_ACCOUNTS",
    "SHOW_AUTH_ACCOUNTS",
    "LIST_AUTH_ACCOUNTS",
    "RETRIEVE_AUTH_ACCOUNTS",
];

export const getGrantsSimiles = [
    "VIEW_AUTH_GRANTS",
    "GET_AUTH_GRANTS",
    "CHECK_AUTH_GRANTS",
    "FETCH_AUTH_GRANTS",
    "READ_AUTH_GRANTS",
    "DISPLAY_AUTH_GRANTS",
    "SHOW_AUTH_GRANTS",
    "LIST_AUTH_GRANTS",
    "RETRIEVE_AUTH_GRANTS",
];

export const getGranterGrantsSimiles = [
    "VIEW_GRANTER_GRANTS",
    "GET_GRANTER_GRANTS",
    "CHECK_GRANTER_GRANTS",
    "FETCH_GRANTER_GRANTS",
    "READ_GRANTER_GRANTS",
    "DISPLAY_GRANTER_GRANTS",
    "SHOW_GRANTER_GRANTS",
    "LIST_GRANTER_GRANTS",
    "RETRIEVE_GRANTER_GRANTS",
];

export const getGranteeGrantsSimiles = [
    "VIEW_GRANTEE_GRANTS",
    "GET_GRANTEE_GRANTS",
    "CHECK_GRANTEE_GRANTS",
    "FETCH_GRANTEE_GRANTS",
    "READ_GRANTEE_GRANTS",
    "DISPLAY_GRANTEE_GRANTS",
    "SHOW_GRANTEE_GRANTS",
    "LIST_GRANTEE_GRANTS",
    "RETRIEVE_GRANTEE_GRANTS",
];

export const msgGrantSimiles = [
    "CREATE_AUTH_GRANT",
    "MAKE_AUTH_GRANT",
    "SET_AUTH_GRANT",
    "START_AUTH_GRANT",
    "BEGIN_AUTH_GRANT",
    "INIT_AUTH_GRANT",
    "ASSIGN_AUTH_GRANT",
    "ENABLE_AUTH_GRANT",
    "REGISTER_AUTH_GRANT",
];

export const msgExecSimiles = [
    "EXECUTE_AUTH_ACTION",
    "RUN_AUTH_ACTION",
    "PERFORM_AUTH_ACTION",
    "START_AUTH_ACTION",
    "BEGIN_AUTH_ACTION",
    "TRIGGER_AUTH_ACTION",
    "LAUNCH_AUTH_ACTION",
    "PROCESS_AUTH_ACTION",
    "INITIATE_AUTH_ACTION",
];

export const msgRevokeSimiles = [
    "REVOKE_AUTH_GRANT",
    "REMOVE_AUTH_GRANT",
    "CANCEL_AUTH_GRANT",
    "DELETE_AUTH_GRANT",
    "STOP_AUTH_GRANT",
    "END_AUTH_GRANT",
    "DISABLE_AUTH_GRANT",
    "WITHDRAW_AUTH_GRANT",
    "TERMINATE_AUTH_GRANT",
];
