export const getBankModuleParamsSimiles = [
    "VIEW_BANK_PARAMS",
    "GET_BANK_PARAMS",
    "CHECK_BANK_PARAMS",
    "FETCH_BANK_PARAMS",
    "READ_BANK_PARAMS",
    "DISPLAY_BANK_PARAMS",
    "SHOW_BANK_PARAMS",
    "LIST_BANK_PARAMS",
    "RETRIEVE_BANK_PARAMS",
];

export const getBankBalanceSimiles = [
    "VIEW_BANK_BALANCE",
    "GET_BANK_BALANCE",
    "CHECK_BANK_BALANCE",
    "FETCH_BANK_BALANCE",
    "READ_BANK_BALANCE",
    "DISPLAY_BANK_BALANCE",
    "SHOW_BANK_BALANCE",
    "LIST_BANK_BALANCE",
    "RETRIEVE_BANK_BALANCE",
];

export const getBankBalancesSimiles = [
    "VIEW_BANK_BALANCES",
    "GET_BANK_BALANCES",
    "CHECK_BANK_BALANCES",
    "FETCH_BANK_BALANCES",
    "READ_BANK_BALANCES",
    "DISPLAY_BANK_BALANCES",
    "SHOW_BANK_BALANCES",
    "LIST_BANK_BALANCES",
    "RETRIEVE_BANK_BALANCES",
];

export const getTotalSupplySimiles = [
    "VIEW_BANK_SUPPLY",
    "GET_BANK_SUPPLY",
    "CHECK_BANK_SUPPLY",
    "FETCH_BANK_SUPPLY",
    "READ_BANK_SUPPLY",
    "DISPLAY_BANK_SUPPLY",
    "SHOW_BANK_SUPPLY",
    "LIST_BANK_SUPPLY",
    "RETRIEVE_BANK_SUPPLY",
];

export const getAllTotalSupplySimiles = [
    "VIEW_BANK_SUPPLIES",
    "GET_BANK_SUPPLIES",
    "CHECK_BANK_SUPPLIES",
    "FETCH_BANK_SUPPLIES",
    "READ_BANK_SUPPLIES",
    "DISPLAY_BANK_SUPPLIES",
    "SHOW_BANK_SUPPLIES",
    "LIST_BANK_SUPPLIES",
    "RETRIEVE_BANK_SUPPLIES",
];

export const getSupplyOfSimiles = [
    "VIEW_TOKEN_SUPPLY",
    "GET_TOKEN_SUPPLY",
    "CHECK_TOKEN_SUPPLY",
    "FETCH_TOKEN_SUPPLY",
    "READ_TOKEN_SUPPLY",
    "DISPLAY_TOKEN_SUPPLY",
    "SHOW_TOKEN_SUPPLY",
    "LIST_TOKEN_SUPPLY",
    "RETRIEVE_TOKEN_SUPPLY",
];

export const getDenomsMetadataSimiles = [
    "VIEW_BANK_DENOMS",
    "GET_BANK_DENOMS",
    "CHECK_BANK_DENOMS",
    "FETCH_BANK_DENOMS",
    "READ_BANK_DENOMS",
    "DISPLAY_BANK_DENOMS",
    "SHOW_BANK_DENOMS",
    "LIST_BANK_DENOMS",
    "RETRIEVE_BANK_DENOMS",
];

export const getDenomMetadataSimiles = [
    "VIEW_BANK_DENOM",
    "GET_BANK_DENOM",
    "CHECK_BANK_DENOM",
    "FETCH_BANK_DENOM",
    "READ_BANK_DENOM",
    "DISPLAY_BANK_DENOM",
    "SHOW_BANK_DENOM",
    "LIST_BANK_DENOM",
    "RETRIEVE_BANK_DENOM",
];

export const getDenomOwnersSimiles = [
    "VIEW_DENOM_OWNERS",
    "GET_DENOM_OWNERS",
    "CHECK_DENOM_OWNERS",
    "FETCH_DENOM_OWNERS",
    "READ_DENOM_OWNERS",
    "DISPLAY_DENOM_OWNERS",
    "SHOW_DENOM_OWNERS",
    "LIST_DENOM_OWNERS",
    "RETRIEVE_DENOM_OWNERS",
];

export const msgSendSimiles = [
    "SEND_BANK_TOKENS",
    "TRANSFER_BANK_TOKENS",
    "MOVE_BANK_TOKENS",
    "SUBMIT_BANK_TRANSFER",
    "CREATE_BANK_TRANSFER",
    "EXECUTE_BANK_TRANSFER",
    "PROCESS_BANK_TRANSFER",
    "INITIATE_BANK_TRANSFER",
    "PERFORM_BANK_TRANSFER",
];

export const msgMultiSendSimiles = [
    "SEND_MULTIPLE_TOKENS",
    "TRANSFER_MULTIPLE_TOKENS",
    "MOVE_MULTIPLE_TOKENS",
    "SUBMIT_MULTIPLE_TRANSFERS",
    "CREATE_MULTIPLE_TRANSFERS",
    "EXECUTE_MULTIPLE_TRANSFERS",
    "PROCESS_MULTIPLE_TRANSFERS",
    "INITIATE_MULTIPLE_TRANSFERS",
    "PERFORM_MULTIPLE_TRANSFERS",
];
