export const getDistributionModuleParamsSimiles = [
    "VIEW_DISTRIBUTION_PARAMS",
    "GET_DISTRIBUTION_PARAMS",
    "CHECK_DISTRIBUTION_PARAMS",
    "FETCH_DISTRIBUTION_PARAMS",
    "READ_DISTRIBUTION_PARAMS",
    "DISPLAY_DISTRIBUTION_PARAMS",
    "SHOW_DISTRIBUTION_PARAMS",
    "LIST_DISTRIBUTION_PARAMS",
    "RETRIEVE_DISTRIBUTION_PARAMS",
];

export const getDelegatorRewardsForValidatorSimiles = [
    "VIEW_VALIDATOR_REWARDS",
    "GET_VALIDATOR_REWARDS",
    "CHECK_VALIDATOR_REWARDS",
    "FETCH_VALIDATOR_REWARDS",
    "READ_VALIDATOR_REWARDS",
    "DISPLAY_VALIDATOR_REWARDS",
    "SHOW_VALIDATOR_REWARDS",
    "LIST_VALIDATOR_REWARDS",
    "RETRIEVE_VALIDATOR_REWARDS",
];

export const getDelegatorRewardsForValidatorNoThrowSimiles = [
    "VIEW_VALIDATOR_REWARDS_SAFE",
    "GET_VALIDATOR_REWARDS_SAFE",
    "CHECK_VALIDATOR_REWARDS_SAFE",
    "FETCH_VALIDATOR_REWARDS_SAFE",
    "READ_VALIDATOR_REWARDS_SAFE",
    "DISPLAY_VALIDATOR_REWARDS_SAFE",
    "SHOW_VALIDATOR_REWARDS_SAFE",
    "LIST_VALIDATOR_REWARDS_SAFE",
    "RETRIEVE_VALIDATOR_REWARDS_SAFE",
];

export const getDelegatorRewardsSimiles = [
    "VIEW_DELEGATOR_REWARDS",
    "GET_DELEGATOR_REWARDS",
    "CHECK_DELEGATOR_REWARDS",
    "FETCH_DELEGATOR_REWARDS",
    "READ_DELEGATOR_REWARDS",
    "DISPLAY_DELEGATOR_REWARDS",
    "SHOW_DELEGATOR_REWARDS",
    "LIST_DELEGATOR_REWARDS",
    "RETRIEVE_DELEGATOR_REWARDS",
];

export const getDelegatorRewardsNoThrowSimiles = [
    "VIEW_DELEGATOR_REWARDS_SAFE",
    "GET_DELEGATOR_REWARDS_SAFE",
    "CHECK_DELEGATOR_REWARDS_SAFE",
    "FETCH_DELEGATOR_REWARDS_SAFE",
    "READ_DELEGATOR_REWARDS_SAFE",
    "DISPLAY_DELEGATOR_REWARDS_SAFE",
    "SHOW_DELEGATOR_REWARDS_SAFE",
    "LIST_DELEGATOR_REWARDS_SAFE",
    "RETRIEVE_DELEGATOR_REWARDS_SAFE",
];

export const msgWithdrawDelegatorRewardSimiles = [
    "WITHDRAW_DELEGATOR_REWARDS",
    "CLAIM_DELEGATOR_REWARDS",
    "COLLECT_DELEGATOR_REWARDS",
    "FETCH_DELEGATOR_REWARDS",
    "REQUEST_DELEGATOR_REWARDS",
    "RETRIEVE_DELEGATOR_REWARDS",
    "PROCESS_DELEGATOR_REWARDS",
    "EXTRACT_DELEGATOR_REWARDS",
    "RELEASE_DELEGATOR_REWARDS",
];

export const msgWithdrawValidatorCommissionSimiles = [
    "WITHDRAW_VALIDATOR_COMMISSION",
    "CLAIM_VALIDATOR_COMMISSION",
    "COLLECT_VALIDATOR_COMMISSION",
    "FETCH_VALIDATOR_COMMISSION",
    "REQUEST_VALIDATOR_COMMISSION",
    "RETRIEVE_VALIDATOR_COMMISSION",
    "PROCESS_VALIDATOR_COMMISSION",
    "EXTRACT_VALIDATOR_COMMISSION",
    "RELEASE_VALIDATOR_COMMISSION",
];
