// Module Parameters and State
export const getModuleParamsSimiles = [
    "VIEW_EXCHANGE_PARAMS",
    "GET_EXCHANGE_PARAMS",
    "CHECK_EXCHANGE_PARAMS",
    "FETCH_EXCHANGE_PARAMS",
    "READ_EXCHANGE_PARAMS",
    "DISPLAY_EXCHANGE_PARAMS",
    "SHOW_EXCHANGE_PARAMS",
    "LIST_EXCHANGE_PARAMS",
    "RETRIEVE_EXCHANGE_PARAMS",
];

export const getModuleStateSimiles = [
    "VIEW_EXCHANGE_STATE",
    "GET_EXCHANGE_STATE",
    "CHECK_EXCHANGE_STATE",
    "FETCH_EXCHANGE_STATE",
    "READ_EXCHANGE_STATE",
    "DISPLAY_EXCHANGE_STATE",
    "SHOW_EXCHANGE_STATE",
    "LIST_EXCHANGE_STATE",
    "RETRIEVE_EXCHANGE_STATE",
];

// Fee Discounts
export const getFeeDiscountScheduleSimiles = [
    "VIEW_DISCOUNT_SCHEDULE",
    "GET_DISCOUNT_SCHEDULE",
    "CHECK_DISCOUNT_SCHEDULE",
    "FETCH_DISCOUNT_SCHEDULE",
    "READ_DISCOUNT_SCHEDULE",
    "DISPLAY_DISCOUNT_SCHEDULE",
    "SHOW_DISCOUNT_SCHEDULE",
    "LIST_DISCOUNT_SCHEDULE",
    "RETRIEVE_DISCOUNT_SCHEDULE",
];

export const getFeeDiscountAccountInfoSimiles = [
    "VIEW_DISCOUNT_INFO",
    "GET_DISCOUNT_INFO",
    "CHECK_DISCOUNT_INFO",
    "FETCH_DISCOUNT_INFO",
    "READ_DISCOUNT_INFO",
    "DISPLAY_DISCOUNT_INFO",
    "SHOW_DISCOUNT_INFO",
    "LIST_DISCOUNT_INFO",
    "RETRIEVE_DISCOUNT_INFO",
];

// Trading Rewards
export const getTradingRewardsCampaignSimiles = [
    "VIEW_REWARDS_CAMPAIGN",
    "GET_REWARDS_CAMPAIGN",
    "CHECK_REWARDS_CAMPAIGN",
    "FETCH_REWARDS_CAMPAIGN",
    "READ_REWARDS_CAMPAIGN",
    "DISPLAY_REWARDS_CAMPAIGN",
    "SHOW_REWARDS_CAMPAIGN",
    "LIST_REWARDS_CAMPAIGN",
    "RETRIEVE_REWARDS_CAMPAIGN",
];

export const getTradeRewardPointsSimiles = [
    "VIEW_REWARD_POINTS",
    "GET_REWARD_POINTS",
    "CHECK_REWARD_POINTS",
    "FETCH_REWARD_POINTS",
    "READ_REWARD_POINTS",
    "DISPLAY_REWARD_POINTS",
    "SHOW_REWARD_POINTS",
    "LIST_REWARD_POINTS",
    "RETRIEVE_REWARD_POINTS",
];

export const getPendingTradeRewardPointsSimiles = [
    "VIEW_PENDING_REWARDS",
    "GET_PENDING_REWARDS",
    "CHECK_PENDING_REWARDS",
    "FETCH_PENDING_REWARDS",
    "READ_PENDING_REWARDS",
    "DISPLAY_PENDING_REWARDS",
    "SHOW_PENDING_REWARDS",
    "LIST_PENDING_REWARDS",
    "RETRIEVE_PENDING_REWARDS",
];

// Orderbooks
export const getDerivativeOrderbooksSimiles = [
    "VIEW_DERIVATIVE_BOOKS",
    "GET_DERIVATIVE_BOOKS",
    "CHECK_DERIVATIVE_BOOKS",
    "FETCH_DERIVATIVE_BOOKS",
    "READ_DERIVATIVE_BOOKS",
    "DISPLAY_DERIVATIVE_BOOKS",
    "SHOW_DERIVATIVE_BOOKS",
    "LIST_DERIVATIVE_BOOKS",
    "RETRIEVE_DERIVATIVE_BOOKS",
];

export const getDerivativeOrderbookSimiles = [
    "VIEW_DERIVATIVE_BOOK",
    "GET_DERIVATIVE_BOOK",
    "CHECK_DERIVATIVE_BOOK",
    "FETCH_DERIVATIVE_BOOK",
    "READ_DERIVATIVE_BOOK",
    "DISPLAY_DERIVATIVE_BOOK",
    "SHOW_DERIVATIVE_BOOK",
    "LIST_DERIVATIVE_BOOK",
    "RETRIEVE_DERIVATIVE_BOOK",
];

export const getSpotOrderbooksSimiles = [
    "VIEW_SPOT_BOOKS",
    "GET_SPOT_BOOKS",
    "CHECK_SPOT_BOOKS",
    "FETCH_SPOT_BOOKS",
    "READ_SPOT_BOOKS",
    "DISPLAY_SPOT_BOOKS",
    "SHOW_SPOT_BOOKS",
    "LIST_SPOT_BOOKS",
    "RETRIEVE_SPOT_BOOKS",
];

export const getSpotOrderbookSimiles = [
    "VIEW_SPOT_BOOK",
    "GET_SPOT_BOOK",
    "CHECK_SPOT_BOOK",
    "FETCH_SPOT_BOOK",
    "READ_SPOT_BOOK",
    "DISPLAY_SPOT_BOOK",
    "SHOW_SPOT_BOOK",
    "LIST_SPOT_BOOK",
    "RETRIEVE_SPOT_BOOK",
];

// Spot Markets
export const getSpotMarketsSimiles = [
    "VIEW_SPOT_MARKETS",
    "GET_SPOT_MARKETS",
    "CHECK_SPOT_MARKETS",
    "FETCH_SPOT_MARKETS",
    "READ_SPOT_MARKETS",
    "DISPLAY_SPOT_MARKETS",
    "SHOW_SPOT_MARKETS",
    "LIST_SPOT_MARKETS",
    "RETRIEVE_SPOT_MARKETS",
];

export const getSpotMarketSimiles = [
    "VIEW_SPOT_MARKET",
    "GET_SPOT_MARKET",
    "CHECK_SPOT_MARKET",
    "FETCH_SPOT_MARKET",
    "READ_SPOT_MARKET",
    "DISPLAY_SPOT_MARKET",
    "SHOW_SPOT_MARKET",
    "LIST_SPOT_MARKET",
    "RETRIEVE_SPOT_MARKET",
];

export const getSpotOrdersSimiles = [
    "VIEW_SPOT_ORDERS",
    "GET_SPOT_ORDERS",
    "CHECK_SPOT_ORDERS",
    "FETCH_SPOT_ORDERS",
    "READ_SPOT_ORDERS",
    "DISPLAY_SPOT_ORDERS",
    "SHOW_SPOT_ORDERS",
    "LIST_SPOT_ORDERS",
    "RETRIEVE_SPOT_ORDERS",
];

export const getSpotOrderHistorySimiles = [
    "VIEW_SPOT_HISTORY",
    "GET_SPOT_HISTORY",
    "CHECK_SPOT_HISTORY",
    "FETCH_SPOT_HISTORY",
    "READ_SPOT_HISTORY",
    "DISPLAY_SPOT_HISTORY",
    "SHOW_SPOT_HISTORY",
    "LIST_SPOT_HISTORY",
    "RETRIEVE_SPOT_HISTORY",
];

export const getSpotTradesSimiles = [
    "VIEW_SPOT_TRADES",
    "GET_SPOT_TRADES",
    "CHECK_SPOT_TRADES",
    "FETCH_SPOT_TRADES",
    "READ_SPOT_TRADES",
    "DISPLAY_SPOT_TRADES",
    "SHOW_SPOT_TRADES",
    "LIST_SPOT_TRADES",
    "RETRIEVE_SPOT_TRADES",
];

// Derivative Markets
export const getDerivativeMarketsSimiles = [
    "VIEW_DERIVATIVE_MARKETS",
    "GET_DERIVATIVE_MARKETS",
    "CHECK_DERIVATIVE_MARKETS",
    "FETCH_DERIVATIVE_MARKETS",
    "READ_DERIVATIVE_MARKETS",
    "DISPLAY_DERIVATIVE_MARKETS",
    "SHOW_DERIVATIVE_MARKETS",
    "LIST_DERIVATIVE_MARKETS",
    "RETRIEVE_DERIVATIVE_MARKETS",
];

export const getDerivativeMarketSimiles = [
    "VIEW_DERIVATIVE_MARKET",
    "GET_DERIVATIVE_MARKET",
    "CHECK_DERIVATIVE_MARKET",
    "FETCH_DERIVATIVE_MARKET",
    "READ_DERIVATIVE_MARKET",
    "DISPLAY_DERIVATIVE_MARKET",
    "SHOW_DERIVATIVE_MARKET",
    "LIST_DERIVATIVE_MARKET",
    "RETRIEVE_DERIVATIVE_MARKET",
];

export const getDerivativeOrdersSimiles = [
    "VIEW_DERIVATIVE_ORDERS",
    "GET_DERIVATIVE_ORDERS",
    "CHECK_DERIVATIVE_ORDERS",
    "FETCH_DERIVATIVE_ORDERS",
    "READ_DERIVATIVE_ORDERS",
    "DISPLAY_DERIVATIVE_ORDERS",
    "SHOW_DERIVATIVE_ORDERS",
    "LIST_DERIVATIVE_ORDERS",
    "RETRIEVE_DERIVATIVE_ORDERS",
];

export const getDerivativeOrderHistorySimiles = [
    "VIEW_DERIVATIVE_ORDER_HISTORY",
    "GET_DERIVATIVE_ORDER_HISTORY",
    "CHECK_DERIVATIVE_ORDER_HISTORY",
    "FETCH_DERIVATIVE_ORDER_HISTORY",
    "READ_DERIVATIVE_ORDER_HISTORY",
    "DISPLAY_DERIVATIVE_ORDER_HISTORY",
    "SHOW_DERIVATIVE_ORDER_HISTORY",
    "LIST_DERIVATIVE_ORDER_HISTORY",
    "RETRIEVE_DERIVATIVE_ORDER_HISTORY",
];

export const getDerivativeTradesSimiles = [
    "VIEW_DERIVATIVE_TRADES",
    "GET_DERIVATIVE_TRADES",
    "CHECK_DERIVATIVE_TRADES",
    "FETCH_DERIVATIVE_TRADES",
    "READ_DERIVATIVE_TRADES",
    "DISPLAY_DERIVATIVE_TRADES",
    "SHOW_DERIVATIVE_TRADES",
    "LIST_DERIVATIVE_TRADES",
    "RETRIEVE_DERIVATIVE_TRADES",
];

// Binary Options
export const getBinaryOptionsMarketsSimiles = [
    "VIEW_BINARY_OPTIONS_MARKET",
    "GET_BINARY_OPTIONS_MARKET",
    "CHECK_BINARY_OPTIONS_MARKET",
    "FETCH_BINARY_OPTIONS_MARKET",
    "READ_BINARY_OPTIONS_MARKET",
    "DISPLAY_BINARY_OPTIONS_MARKET",
    "SHOW_BINARY_OPTIONS_MARKET",
    "LIST_BINARY_OPTIONS_MARKET",
    "RETRIEVE_BINARY_OPTIONS_MARKET",
];

export const getBinaryOptionsMarketSimiles = [
    "VIEW_BINARY_OPTIONS",
    "GET_BINARY_OPTIONS",
    "CHECK_BINARY_OPTIONS",
    "FETCH_BINARY_OPTIONS",
    "READ_BINARY_OPTIONS",
    "DISPLAY_BINARY_OPTIONS",
    "SHOW_BINARY_OPTIONS",
    "LIST_BINARY_OPTIONS",
    "RETRIEVE_BINARY_OPTIONS",
];

// Positions
export const getExchangePositionsSimiles = [
    "VIEW_EXCHANGE_POSITIONS",
    "GET_EXCHANGE_POSITIONS",
    "CHECK_EXCHANGE_POSITIONS",
    "FETCH_EXCHANGE_POSITIONS",
    "READ_EXCHANGE_POSITIONS",
    "DISPLAY_EXCHANGE_POSITIONS",
    "SHOW_EXCHANGE_POSITIONS",
    "LIST_EXCHANGE_POSITIONS",
    "RETRIEVE_EXCHANGE_POSITIONS",
];
// Positions
export const getUserPositionsSimiles = [
    "VIEW_USER_POSITIONS",
    "GET_USER_POSITIONS",
    "CHECK_USER_POSITIONS",
    "FETCH_USER_POSITIONS",
    "READ_USER_POSITIONS",
    "DISPLAY_USER_POSITIONS",
    "SHOW_USER_POSITIONS",
    "LIST_USER_POSITIONS",
    "RETRIEVE_USER_POSITIONS",
];

// Funding
export const getFundingPaymentsSimiles = [
    "VIEW_FUNDING_PAYMENTS",
    "GET_FUNDING_PAYMENTS",
    "CHECK_FUNDING_PAYMENTS",
    "FETCH_FUNDING_PAYMENTS",
    "READ_FUNDING_PAYMENTS",
    "DISPLAY_FUNDING_PAYMENTS",
    "SHOW_FUNDING_PAYMENTS",
    "LIST_FUNDING_PAYMENTS",
    "RETRIEVE_FUNDING_PAYMENTS",
];

export const getFundingRatesSimiles = [
    "VIEW_FUNDING_RATES",
    "GET_FUNDING_RATES",
    "CHECK_FUNDING_RATES",
    "FETCH_FUNDING_RATES",
    "READ_FUNDING_RATES",
    "DISPLAY_FUNDING_RATES",
    "SHOW_FUNDING_RATES",
    "LIST_FUNDING_RATES",
    "RETRIEVE_FUNDING_RATES",
];

// Subaccounts
export const getSubaccountTradeNonceSimiles = [
    "VIEW_TRADE_NONCE",
    "GET_TRADE_NONCE",
    "CHECK_TRADE_NONCE",
    "FETCH_TRADE_NONCE",
    "READ_TRADE_NONCE",
    "DISPLAY_TRADE_NONCE",
    "SHOW_TRADE_NONCE",
    "LIST_TRADE_NONCE",
    "RETRIEVE_TRADE_NONCE",
];

export const getSubaccountsListSimiles = [
    "VIEW_SUBACCOUNT_LIST",
    "GET_SUBACCOUNT_LIST",
    "CHECK_SUBACCOUNT_LIST",
    "FETCH_SUBACCOUNT_LIST",
    "READ_SUBACCOUNT_LIST",
    "DISPLAY_SUBACCOUNT_LIST",
    "SHOW_SUBACCOUNT_LIST",
    "LIST_SUBACCOUNT_LIST",
    "RETRIEVE_SUBACCOUNT_LIST",
];

export const getSubaccountBalancesListSimiles = [
    "VIEW_SUBACCOUNT_BALANCES",
    "GET_SUBACCOUNT_BALANCES",
    "CHECK_SUBACCOUNT_BALANCES",
    "FETCH_SUBACCOUNT_BALANCES",
    "READ_SUBACCOUNT_BALANCES",
    "DISPLAY_SUBACCOUNT_BALANCES",
    "SHOW_SUBACCOUNT_BALANCES",
    "LIST_SUBACCOUNT_BALANCES",
    "RETRIEVE_SUBACCOUNT_BALANCES",
];

export const getSubaccountHistorySimiles = [
    "VIEW_SUBACCOUNT_HISTORY",
    "GET_SUBACCOUNT_HISTORY",
    "CHECK_SUBACCOUNT_HISTORY",
    "FETCH_SUBACCOUNT_HISTORY",
    "READ_SUBACCOUNT_HISTORY",
    "DISPLAY_SUBACCOUNT_HISTORY",
    "SHOW_SUBACCOUNT_HISTORY",
    "LIST_SUBACCOUNT_HISTORY",
    "RETRIEVE_SUBACCOUNT_HISTORY",
];

export const getSubaccountOrderSummarySimiles = [
    "VIEW_ORDER_SUMMARY",
    "GET_ORDER_SUMMARY",
    "CHECK_ORDER_SUMMARY",
    "FETCH_ORDER_SUMMARY",
    "READ_ORDER_SUMMARY",
    "DISPLAY_ORDER_SUMMARY",
    "SHOW_ORDER_SUMMARY",
    "LIST_ORDER_SUMMARY",
    "RETRIEVE_ORDER_SUMMARY",
];

export const getOrderStatesSimiles = [
    "VIEW_ORDER_STATE",
    "GET_ORDER_STATE",
    "CHECK_ORDER_STATE",
    "FETCH_ORDER_STATE",
    "READ_ORDER_STATE",
    "DISPLAY_ORDER_STATE",
    "SHOW_ORDER_STATE",
    "LIST_ORDER_STATE",
    "RETRIEVE_ORDER_STATE",
];

export const getIsOptedOutOfRewardsSimiles = [
    "GET_IS_OPTED_OUT_OF_REWARDS",
    "VIEW_IS_OPTED_OUT_OF_REWARDS",
    "CHECK_IS_OPTED_OUT_OF_REWARDS",
    "FETCH_IS_OPTED_OUT_OF_REWARDS",
    "READ_IS_OPTED_OUT_OF_REWARDS",
    "DISPLAY_IS_OPTED_OUT_OF_REWARDS",
    "SHOW_IS_OPTED_OUT_OF_REWARDS",
    "LIST_IS_OPTED_OUT_OF_REWARDS",
];

// Portfolio
export const getAccountPortfolioSimiles = [
    "VIEW_ACCOUNT_PORTFOLIO",
    "GET_ACCOUNT_PORTFOLIO",
    "CHECK_ACCOUNT_PORTFOLIO",
    "FETCH_ACCOUNT_PORTFOLIO",
    "READ_ACCOUNT_PORTFOLIO",
    "DISPLAY_ACCOUNT_PORTFOLIO",
    "SHOW_ACCOUNT_PORTFOLIO",
    "LIST_ACCOUNT_PORTFOLIO",
    "RETRIEVE_ACCOUNT_PORTFOLIO",
];

export const getAccountPortfolioBalancesSimiles = [
    "VIEW_PORTFOLIO_BALANCES",
    "GET_PORTFOLIO_BALANCES",
    "CHECK_PORTFOLIO_BALANCES",
    "FETCH_PORTFOLIO_BALANCES",
    "READ_PORTFOLIO_BALANCES",
    "DISPLAY_PORTFOLIO_BALANCES",
    "SHOW_PORTFOLIO_BALANCES",
    "LIST_PORTFOLIO_BALANCES",
    "RETRIEVE_PORTFOLIO_BALANCES",
];

// Historical Data
export const getHistoricalBalanceSimiles = [
    "VIEW_HISTORICAL_BALANCE",
    "GET_HISTORICAL_BALANCE",
    "CHECK_HISTORICAL_BALANCE",
    "FETCH_HISTORICAL_BALANCE",
    "READ_HISTORICAL_BALANCE",
    "DISPLAY_HISTORICAL_BALANCE",
    "SHOW_HISTORICAL_BALANCE",
    "LIST_HISTORICAL_BALANCE",
    "RETRIEVE_HISTORICAL_BALANCE",
];

export const getHistoricalRpnlSimiles = [
    "VIEW_HISTORICAL_RPNL",
    "GET_HISTORICAL_RPNL",
    "CHECK_HISTORICAL_RPNL",
    "FETCH_HISTORICAL_RPNL",
    "READ_HISTORICAL_RPNL",
    "DISPLAY_HISTORICAL_RPNL",
    "SHOW_HISTORICAL_RPNL",
    "LIST_HISTORICAL_RPNL",
    "RETRIEVE_HISTORICAL_RPNL",
];
// Leaderboard
export const getPnlLeaderboardSimiles = [
    "VIEW_PNL_LEADERBOARD",
    "GET_PNL_LEADERBOARD",
    "CHECK_PNL_LEADERBOARD",
    "FETCH_PNL_LEADERBOARD",
    "READ_PNL_LEADERBOARD",
    "DISPLAY_PNL_LEADERBOARD",
    "SHOW_PNL_LEADERBOARD",
    "LIST_PNL_LEADERBOARD",
    "RETRIEVE_PNL_LEADERBOARD",
];

export const getVolLeaderboardSimiles = [
    "VIEW_VOLUME_LEADERBOARD",
    "GET_VOLUME_LEADERBOARD",
    "CHECK_VOLUME_LEADERBOARD",
    "FETCH_VOLUME_LEADERBOARD",
    "READ_VOLUME_LEADERBOARD",
    "DISPLAY_VOLUME_LEADERBOARD",
    "SHOW_VOLUME_LEADERBOARD",
    "LIST_VOLUME_LEADERBOARD",
    "RETRIEVE_VOLUME_LEADERBOARD",
];

// Message Actions - Order Management
export const msgBatchCancelBinaryOptionsOrdersSimiles = [
    "BATCH_CANCEL_BINARY_OPTIONS_ORDERS",
    "BATCH_REMOVE_BINARY_OPTIONS_ORDERS",
    "BATCH_DELETE_BINARY_OPTIONS_ORDERS",
    "BATCH_STOP_BINARY_OPTIONS_ORDERS",
    "BATCH_END_BINARY_OPTIONS_ORDERS",
    "BATCH_CLEAR_BINARY_OPTIONS_ORDERS",
    "BATCH_TERMINATE_BINARY_OPTIONS_ORDERS",
    "BATCH_HALT_BINARY_OPTIONS_ORDERS",
    "BATCH_CLOSE_BINARY_OPTIONS_ORDERS",
];

export const msgBatchCancelDerivativeOrdersSimiles = [
    "BATCH_CANCEL_DERIVATIVE_ORDERS",
    "BATCH_REMOVE_DERIVATIVE_ORDERS",
    "BATCH_DELETE_DERIVATIVE_ORDERS",
    "BATCH_STOP_DERIVATIVE_ORDERS",
    "BATCH_END_DERIVATIVE_ORDERS",
    "BATCH_CLEAR_DERIVATIVE_ORDERS",
    "BATCH_TERMINATE_DERIVATIVE_ORDERS",
    "BATCH_HALT_DERIVATIVE_ORDERS",
    "BATCH_CLOSE_DERIVATIVE_ORDERS",
];

export const msgBatchCancelSpotOrdersSimiles = [
    "BATCH_CANCEL_SPOT_ORDERS",
    "BATCH_REMOVE_SPOT_ORDERS",
    "BATCH_DELETE_SPOT_ORDERS",
    "BATCH_STOP_SPOT_ORDERS",
    "BATCH_END_SPOT_ORDERS",
    "BATCH_CLEAR_SPOT_ORDERS",
    "BATCH_TERMINATE_SPOT_ORDERS",
    "BATCH_HALT_SPOT_ORDERS",
    "BATCH_CLOSE_SPOT_ORDERS",
];

// Message Actions - Creating Orders
export const msgCreateBinaryOptionsLimitOrderSimiles = [
    "CREATE_BINARY_OPTIONS_LIMIT_ORDERS",
    "PLACE_BINARY_OPTIONS_LIMIT_ORDERS",
    "SUBMIT_BINARY_OPTIONS_LIMIT_ORDERS",
    "START_BINARY_OPTIONS_LIMIT_ORDERS",
    "OPEN_BINARY_OPTIONS_LIMIT_ORDERS",
    "SET_BINARY_OPTIONS_LIMIT_ORDERS",
    "MAKE_BINARY_OPTIONS_LIMIT_ORDERS",
    "INITIALIZE_BINARY_OPTIONS_LIMIT_ORDERS",
    "BEGIN_BINARY_OPTIONS_LIMIT_ORDERS",
];

export const msgCreateBinaryOptionsMarketOrderSimiles = [
    "CREATE_BINARY_OPTIONS_ORDERS",
    "PLACE_BINARY_OPTIONS_ORDERS",
    "SUBMIT_BINARY_OPTIONS_ORDERS",
    "START_BINARY_OPTIONS_ORDERS",
    "OPEN_BINARY_OPTIONS_ORDERS",
    "SET_BINARY_OPTIONS_ORDERS",
    "MAKE_BINARY_OPTIONS_ORDERS",
    "INITIALIZE_BINARY_OPTIONS_ORDERS",
    "BEGIN_BINARY_OPTIONS_ORDERS",
];

export const msgCreateDerivativeLimitOrderSimiles = [
    "CREATE_DERIVATIVE_LIMIT_ORDERS",
    "PLACE_DERIVATIVE_LIMIT_ORDERS",
    "SUBMIT_DERIVATIVE_LIMIT_ORDERS",
    "START_DERIVATIVE_LIMIT_ORDERS",
    "OPEN_DERIVATIVE_LIMIT_ORDERS",
    "SET_DERIVATIVE_LIMIT_ORDERS",
    "MAKE_DERIVATIVE_LIMIT_ORDERS",
    "INITIALIZE_DERIVATIVE_LIMIT_ORDERS",
    "BEGIN_DERIVATIVE_LIMIT_ORDERS",
];

export const msgCreateDerivativeMarketOrderSimiles = [
    "CREATE_DERIVATIVE_MARKET_ORDERS",
    "PLACE_DERIVATIVE_MARKET_ORDERS",
    "SUBMIT_DERIVATIVE_MARKET_ORDERS",
    "START_DERIVATIVE_MARKET_ORDERS",
    "OPEN_DERIVATIVE_MARKET_ORDERS",
    "SET_DERIVATIVE_MARKET_ORDERS",
    "MAKE_DERIVATIVE_MARKET_ORDERS",
    "INITIALIZE_DERIVATIVE_MARKET_ORDERS",
    "BEGIN_DERIVATIVE_MARKET_ORDERS",
];

export const msgCreateSpotLimitOrderSimiles = [
    "CREATE_SPOT_LIMIT_ORDERS",
    "PLACE_SPOT_LIMIT_ORDERS",
    "SUBMIT_SPOT_LIMIT_ORDERS",
    "START_SPOT_LIMIT_ORDERS",
    "OPEN_SPOT_LIMIT_ORDERS",
    "SET_SPOT_LIMIT_ORDERS",
    "MAKE_SPOT_LIMIT_ORDERS",
    "INITIALIZE_SPOT_LIMIT_ORDERS",
    "BEGIN_SPOT_LIMIT_ORDERS",
];

export const msgCreateSpotMarketOrderSimiles = [
    "CREATE_SPOT_MARKET_ORDERS",
    "PLACE_SPOT_MARKET_ORDERS",
    "SUBMIT_SPOT_MARKET_ORDERS",
    "START_SPOT_MARKET_ORDERS",
    "OPEN_SPOT_MARKET_ORDERS",
    "SET_SPOT_MARKET_ORDERS",
    "MAKE_SPOT_MARKET_ORDERS",
    "INITIALIZE_SPOT_MARKET_ORDERS",
    "BEGIN_SPOT_MARKET_ORDERS",
];
// Deposit and Withdrawal Actions
export const msgDepositSimiles = [
    "CREATE_EXCHANGE_DEPOSIT",
    "MAKE_EXCHANGE_DEPOSIT",
    "SUBMIT_EXCHANGE_DEPOSIT",
    "START_EXCHANGE_DEPOSIT",
    "OPEN_EXCHANGE_DEPOSIT",
    "SET_EXCHANGE_DEPOSIT",
    "PROCESS_EXCHANGE_DEPOSIT",
    "INITIALIZE_EXCHANGE_DEPOSIT",
    "BEGIN_EXCHANGE_DEPOSIT",
];

export const msgWithdrawSimiles = [
    "CREATE_EXCHANGE_WITHDRAWAL",
    "MAKE_EXCHANGE_WITHDRAWAL",
    "SUBMIT_EXCHANGE_WITHDRAWAL",
    "START_EXCHANGE_WITHDRAWAL",
    "OPEN_EXCHANGE_WITHDRAWAL",
    "SET_EXCHANGE_WITHDRAWAL",
    "PROCESS_EXCHANGE_WITHDRAWAL",
    "INITIALIZE_EXCHANGE_WITHDRAWAL",
    "BEGIN_EXCHANGE_WITHDRAWAL",
];

// Position Management Actions
export const msgIncreasePositionMarginSimiles = [
    "INCREASE_POSITION_MARGIN",
    "ADD_POSITION_MARGIN",
    "RAISE_POSITION_MARGIN",
    "BOOST_POSITION_MARGIN",
    "EXPAND_POSITION_MARGIN",
    "EXTEND_POSITION_MARGIN",
    "ENHANCE_POSITION_MARGIN",
    "GROW_POSITION_MARGIN",
    "LIFT_POSITION_MARGIN",
];

export const msgLiquidatePositionSimiles = [
    "LIQUIDATE_EXCHANGE_POSITION",
    "END_EXCHANGE_POSITION",
    "TERMINATE_EXCHANGE_POSITION",
    "FINISH_EXCHANGE_POSITION",
    "CLEAR_EXCHANGE_POSITION",
    "COMPLETE_EXCHANGE_POSITION",
    "RESOLVE_EXCHANGE_POSITION",
    "SETTLE_EXCHANGE_POSITION",
];

// Administrative Actions
export const msgInstantSpotMarketLaunchSimiles = [
    "LAUNCH_SPOT_MARKET",
    "START_SPOT_MARKET",
    "CREATE_SPOT_MARKET",
    "OPEN_SPOT_MARKET",
    "INITIALIZE_SPOT_MARKET",
    "BEGIN_SPOT_MARKET",
    "DEPLOY_SPOT_MARKET",
    "ESTABLISH_SPOT_MARKET",
    "ACTIVATE_SPOT_MARKET",
];

export const msgReclaimLockedFundsSimiles = [
    "RECLAIM_LOCKED_FUNDS",
    "RECOVER_LOCKED_FUNDS",
    "RETRIEVE_LOCKED_FUNDS",
    "RELEASE_LOCKED_FUNDS",
    "RESTORE_LOCKED_FUNDS",
    "RETURN_LOCKED_FUNDS",
    "UNLOCK_LOCKED_FUNDS",
    "FREE_LOCKED_FUNDS",
    "COLLECT_LOCKED_FUNDS",
];

export const msgRewardsOptOutSimiles = [
    "DISABLE_EXCHANGE_REWARDS",
    "STOP_EXCHANGE_REWARDS",
    "EXIT_EXCHANGE_REWARDS",
    "LEAVE_EXCHANGE_REWARDS",
    "QUIT_EXCHANGE_REWARDS",
    "END_EXCHANGE_REWARDS",
    "WITHDRAW_EXCHANGE_REWARDS",
    "ABANDON_EXCHANGE_REWARDS",
    "DECLINE_EXCHANGE_REWARDS",
];

export const msgSignDataSimiles = [
    "SIGN_EXCHANGE_DATA",
    "AUTHORIZE_EXCHANGE_DATA",
    "APPROVE_EXCHANGE_DATA",
    "VALIDATE_EXCHANGE_DATA",
    "CONFIRM_EXCHANGE_DATA",
    "VERIFY_EXCHANGE_DATA",
    "ENDORSE_EXCHANGE_DATA",
    "CERTIFY_EXCHANGE_DATA",
    "AUTHENTICATE_EXCHANGE_DATA",
];

export const msgExternalTransferSimiles = [
    "CREATE_EXTERNAL_TRANSFER",
    "MAKE_EXTERNAL_TRANSFER",
    "SUBMIT_EXTERNAL_TRANSFER",
    "START_EXTERNAL_TRANSFER",
    "PROCESS_EXTERNAL_TRANSFER",
    "INITIATE_EXTERNAL_TRANSFER",
    "BEGIN_EXTERNAL_TRANSFER",
    "EXECUTE_EXTERNAL_TRANSFER",
    "PERFORM_EXTERNAL_TRANSFER",
];

export const msgAdminUpdateBinaryOptionsMarketSimiles = [
    "UPDATE_BINARY_OPTIONS",
    "MODIFY_BINARY_OPTIONS",
    "CHANGE_BINARY_OPTIONS",
    "ADJUST_BINARY_OPTIONS",
    "EDIT_BINARY_OPTIONS",
    "REVISE_BINARY_OPTIONS",
    "ALTER_BINARY_OPTIONS",
    "AMEND_BINARY_OPTIONS",
    "CONFIGURE_BINARY_OPTIONS",
];
export const getRewardsSimiles = [
    "VIEW_EXCHANGE_REWARDS",
    "GET_EXCHANGE_REWARDS",
    "CHECK_EXCHANGE_REWARDS",
    "FETCH_EXCHANGE_REWARDS",
    "READ_EXCHANGE_REWARDS",
    "DISPLAY_EXCHANGE_REWARDS",
    "SHOW_EXCHANGE_REWARDS",
    "LIST_EXCHANGE_REWARDS",
    "RETRIEVE_EXCHANGE_REWARDS",
];

export const getAtomicSwapHistorySimiles = [
    "VIEW_ATOMIC_SWAPS",
    "GET_ATOMIC_SWAPS",
    "CHECK_ATOMIC_SWAPS",
    "FETCH_ATOMIC_SWAPS",
    "READ_ATOMIC_SWAPS",
    "DISPLAY_ATOMIC_SWAPS",
    "SHOW_ATOMIC_SWAPS",
    "LIST_ATOMIC_SWAPS",
    "RETRIEVE_ATOMIC_SWAPS",
];

export const getGridStrategiesSimiles = [
    "VIEW_GRID_STRATEGIES",
    "GET_GRID_STRATEGIES",
    "CHECK_GRID_STRATEGIES",
    "FETCH_GRID_STRATEGIES",
    "READ_GRID_STRATEGIES",
    "DISPLAY_GRID_STRATEGIES",
    "SHOW_GRID_STRATEGIES",
    "LIST_GRID_STRATEGIES",
    "RETRIEVE_GRID_STRATEGIES",
];

export const getHistoricalVolumesSimiles = [
    "VIEW_HISTORICAL_VOLUMES",
    "GET_HISTORICAL_VOLUMES",
    "CHECK_HISTORICAL_VOLUMES",
    "FETCH_HISTORICAL_VOLUMES",
    "READ_HISTORICAL_VOLUMES",
    "DISPLAY_HISTORICAL_VOLUMES",
    "SHOW_HISTORICAL_VOLUMES",
    "LIST_HISTORICAL_VOLUMES",
    "RETRIEVE_HISTORICAL_VOLUMES",
];

export const getPnlLeaderboardFixedResolutionSimiles = [
    "VIEW_FIXED_RESOLUTION_LEADERBOARD",
    "GET_FIXED_RESOLUTION_LEADERBOARD",
    "CHECK_FIXED_RESOLUTION_LEADERBOARD",
    "FETCH_FIXED_RESOLUTION_LEADERBOARD",
    "READ_FIXED_RESOLUTION_LEADERBOARD",
    "DISPLAY_FIXED_RESOLUTION_LEADERBOARD",
    "SHOW_FIXED_RESOLUTION_LEADERBOARD",
    "LIST_FIXED_RESOLUTION_LEADERBOARD",
    "RETRIEVE_FIXED_RESOLUTION_LEADERBOARD",
];

export const getVolLeaderboardFixedResolutionSimiles = [
    "VIEW_VOLUME_FIXED",
    "GET_VOLUME_FIXED",
    "CHECK_VOLUME_FIXED",
    "FETCH_VOLUME_FIXED",
    "READ_VOLUME_FIXED",
    "DISPLAY_VOLUME_FIXED",
    "SHOW_VOLUME_FIXED",
    "LIST_VOLUME_FIXED",
    "RETRIEVE_VOLUME_FIXED",
];

export const getDenomHoldersSimiles = [
    "VIEW_DENOM_HOLDERS",
    "GET_DENOM_HOLDERS",
    "CHECK_DENOM_HOLDERS",
    "FETCH_DENOM_HOLDERS",
    "READ_DENOM_HOLDERS",
    "DISPLAY_DENOM_HOLDERS",
    "SHOW_DENOM_HOLDERS",
    "LIST_DENOM_HOLDERS",
    "RETRIEVE_DENOM_HOLDERS",
];

export const msgBatchUpdateOrdersSimiles = [
    "UPDATE_ORDER_BATCH",
    "MODIFY_ORDER_BATCH",
    "CHANGE_ORDER_BATCH",
    "ADJUST_ORDER_BATCH",
    "EDIT_ORDER_BATCH",
    "REVISE_ORDER_BATCH",
    "ALTER_ORDER_BATCH",
    "AMEND_ORDER_BATCH",
    "CONFIGURE_ORDER_BATCH",
];

export const msgCancelBinaryOptionsOrderSimiles = [
    "CANCEL_BINARY_OPTIONS_ORDER",
    "REMOVE_BINARY_OPTIONS_ORDER",
    "DELETE_BINARY_OPTIONS_ORDER",
    "STOP_BINARY_OPTIONS_ORDER",
    "END_BINARY_OPTIONS_ORDER",
    "CLEAR_BINARY_OPTIONS_ORDER",
    "TERMINATE_BINARY_OPTIONS_ORDER",
    "HALT_BINARY_OPTIONS_ORDER",
    "CLOSE_BINARY_OPTIONS_ORDER",
];

export const msgCancelDerivativeOrderSimiles = [
    "CANCEL_DERIVATIVE_ORDER",
    "REMOVE_DERIVATIVE_ORDER",
    "DELETE_DERIVATIVE_ORDER",
    "STOP_DERIVATIVE_ORDER",
    "END_DERIVATIVE_ORDER",
    "CLEAR_DERIVATIVE_ORDER",
    "TERMINATE_DERIVATIVE_ORDER",
    "HALT_DERIVATIVE_ORDER",
    "CLOSE_DERIVATIVE_ORDER",
];

export const msgCancelSpotOrderSimiles = [
    "CANCEL_SPOT_ORDER",
    "REMOVE_SPOT_ORDER",
    "DELETE_SPOT_ORDER",
    "STOP_SPOT_ORDER",
    "END_SPOT_ORDER",
    "CLEAR_SPOT_ORDER",
    "TERMINATE_SPOT_ORDER",
    "HALT_SPOT_ORDER",
    "CLOSE_SPOT_ORDER",
];
