export const getTxByHashSimiles = [
    "VIEW_TRANSACTION_BY_HASH_BY_HASH",
    "GET_TRANSACTION_BY_HASH",
    "CHECK_TRANSACTION_BY_HASH",
    "FETCH_TRANSACTION_BY_HASH",
    "READ_TRANSACTION_BY_HASH",
    "DISPLAY_TRANSACTION_BY_HASH",
    "SHOW_TRANSACTION_BY_HASH",
    "LIST_TRANSACTION_BY_HASH",
    "RETRIEVE_TRANSACTION_BY_HASH",
];

export const getAccountTxSimiles = [
    "VIEW_ACCOUNT_TRANSACTIONS",
    "GET_ACCOUNT_TRANSACTIONS",
    "CHECK_ACCOUNT_TRANSACTIONS",
    "FETCH_ACCOUNT_TRANSACTIONS",
    "READ_ACCOUNT_TRANSACTIONS",
    "DISPLAY_ACCOUNT_TRANSACTIONS",
    "SHOW_ACCOUNT_TRANSACTIONS",
    "LIST_ACCOUNT_TRANSACTIONS",
    "RETRIEVE_ACCOUNT_TRANSACTIONS",
];

export const getExplorerValidatorSimiles = [
    "VIEW_EXPLORER_EXPLORER_VALIDATOR",
    "GET_EXPLORER_EXPLORER_VALIDATOR",
    "CHECK_EXPLORER_VALIDATOR",
    "FETCH_EXPLORER_VALIDATOR",
    "READ_EXPLORER_VALIDATOR",
    "DISPLAY_EXPLORER_VALIDATOR",
    "SHOW_EXPLORER_VALIDATOR",
    "LIST_EXPLORER_VALIDATOR",
    "RETRIEVE_EXPLORER_VALIDATOR",
];

export const getExplorerValidatorUptimeSimiles = [
    "VIEW_EXPLORER_VALIDATOR_UPTIME",
    "GET_EXPLORER_VALIDATOR_UPTIME",
    "CHECK_EXPLORER_VALIDATOR_UPTIME",
    "FETCH_EXPLORER_VALIDATOR_UPTIME",
    "READ_EXPLORER_VALIDATOR_UPTIME",
    "DISPLAY_EXPLORER_VALIDATOR_UPTIME",
    "SHOW_EXPLORER_VALIDATOR_UPTIME",
    "LIST_EXPLORER_VALIDATOR_UPTIME",
    "RETRIEVE_EXPLORER_VALIDATOR_UPTIME",
];

export const getPeggyDepositTxsSimiles = [
    "VIEW_PEGGY_DEPOSITS",
    "GET_PEGGY_DEPOSITS",
    "CHECK_PEGGY_DEPOSITS",
    "FETCH_PEGGY_DEPOSITS",
    "READ_PEGGY_DEPOSITS",
    "DISPLAY_PEGGY_DEPOSITS",
    "SHOW_PEGGY_DEPOSITS",
    "LIST_PEGGY_DEPOSITS",
    "RETRIEVE_PEGGY_DEPOSITS",
];

export const getPeggyWithdrawalTxsSimiles = [
    "VIEW_PEGGY_WITHDRAWALS",
    "GET_PEGGY_WITHDRAWALS",
    "CHECK_PEGGY_WITHDRAWALS",
    "FETCH_PEGGY_WITHDRAWALS",
    "READ_PEGGY_WITHDRAWALS",
    "DISPLAY_PEGGY_WITHDRAWALS",
    "SHOW_PEGGY_WITHDRAWALS",
    "LIST_PEGGY_WITHDRAWALS",
    "RETRIEVE_PEGGY_WITHDRAWALS",
];

export const getBlocksSimiles = [
    "VIEW_BLOCKS",
    "GET_BLOCKS",
    "CHECK_BLOCKS",
    "FETCH_BLOCKS",
    "READ_BLOCKS",
    "DISPLAY_BLOCKS",
    "SHOW_BLOCKS",
    "LIST_BLOCKS",
    "RETRIEVE_BLOCKS",
];

export const getBlockSimiles = [
    "VIEW_BLOCK",
    "GET_BLOCK",
    "CHECK_BLOCK",
    "FETCH_BLOCK",
    "READ_BLOCK",
    "DISPLAY_BLOCK",
    "SHOW_BLOCK",
    "LIST_BLOCK",
    "RETRIEVE_BLOCK",
];

export const getTxsSimiles = [
    "VIEW_TRANSACTIONS",
    "GET_TRANSACTIONS",
    "CHECK_TRANSACTIONS",
    "FETCH_TRANSACTIONS",
    "READ_TRANSACTIONS",
    "DISPLAY_TRANSACTIONS",
    "SHOW_TRANSACTIONS",
    "LIST_TRANSACTIONS",
    "RETRIEVE_TRANSACTIONS",
];

export const getIBCTransferTxsSimiles = [
    "VIEW_IBC_TRANSFERS",
    "GET_IBC_TRANSFERS",
    "CHECK_IBC_TRANSFERS",
    "FETCH_IBC_TRANSFERS",
    "READ_IBC_TRANSFERS",
    "DISPLAY_IBC_TRANSFERS",
    "SHOW_IBC_TRANSFERS",
    "LIST_IBC_TRANSFERS",
    "RETRIEVE_IBC_TRANSFERS",
];

export const getExplorerStatsSimiles = [
    "VIEW_EXPLORER_STATS",
    "GET_EXPLORER_STATS",
    "CHECK_EXPLORER_STATS",
    "FETCH_EXPLORER_STATS",
    "READ_EXPLORER_STATS",
    "DISPLAY_EXPLORER_STATS",
    "SHOW_EXPLORER_STATS",
    "LIST_EXPLORER_STATS",
    "RETRIEVE_EXPLORER_STATS",
];
