export const getGovernanceModuleParamsSimiles = [
    "VIEW_GOVERNANCE_PARAMS",
    "GET_GOVERNANCE_PARAMS",
    "CHECK_GOVERNANCE_PARAMS",
    "FETCH_GOVERNANCE_PARAMS",
    "READ_GOVERNANCE_PARAMS",
    "DISPLAY_GOVERNANCE_PARAMS",
    "SHOW_GOVERNANCE_PARAMS",
    "LIST_GOVERNANCE_PARAMS",
    "RETRIEVE_GOVERNANCE_PARAMS",
];

export const getProposalsSimiles = [
    "VIEW_PROPOSALS",
    "GET_PROPOSALS",
    "CHECK_PROPOSALS",
    "FETCH_PROPOSALS",
    "READ_PROPOSALS",
    "DISPLAY_PROPOSALS",
    "SHOW_PROPOSALS",
    "LIST_PROPOSALS",
    "RETRIEVE_PROPOSALS",
];

export const getProposalSimiles = [
    "VIEW_PROPOSAL",
    "GET_PROPOSAL",
    "CHECK_PROPOSAL",
    "FETCH_PROPOSAL",
    "READ_PROPOSAL",
    "DISPLAY_PROPOSAL",
    "SHOW_PROPOSAL",
    "LIST_PROPOSAL",
    "RETRIEVE_PROPOSAL",
];

export const getProposalDepositsSimiles = [
    "VIEW_PROPOSAL_DEPOSITS",
    "GET_PROPOSAL_DEPOSITS",
    "CHECK_PROPOSAL_DEPOSITS",
    "FETCH_PROPOSAL_DEPOSITS",
    "READ_PROPOSAL_DEPOSITS",
    "DISPLAY_PROPOSAL_DEPOSITS",
    "SHOW_PROPOSAL_DEPOSITS",
    "LIST_PROPOSAL_DEPOSITS",
    "RETRIEVE_PROPOSAL_DEPOSITS",
];

export const getProposalVotesSimiles = [
    "VIEW_PROPOSAL_VOTES",
    "GET_PROPOSAL_VOTES",
    "CHECK_PROPOSAL_VOTES",
    "FETCH_PROPOSAL_VOTES",
    "READ_PROPOSAL_VOTES",
    "DISPLAY_PROPOSAL_VOTES",
    "SHOW_PROPOSAL_VOTES",
    "LIST_PROPOSAL_VOTES",
    "RETRIEVE_PROPOSAL_VOTES",
];

export const getProposalTallySimiles = [
    "VIEW_PROPOSAL_TALLY",
    "GET_PROPOSAL_TALLY",
    "CHECK_PROPOSAL_TALLY",
    "FETCH_PROPOSAL_TALLY",
    "READ_PROPOSAL_TALLY",
    "DISPLAY_PROPOSAL_TALLY",
    "SHOW_PROPOSAL_TALLY",
    "LIST_PROPOSAL_TALLY",
    "RETRIEVE_PROPOSAL_TALLY",
];

export const msgSubmitProposalExpiryFuturesMarketLaunchSimiles = [
    "SUBMIT_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "CREATE_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "INITIALIZE_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "START_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "LAUNCH_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "PROPOSE_EXPIRY_FUTURES_MARKET_MARKET",
    "BEGIN_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "ESTABLISH_EXPIRY_FUTURES_MARKET_PROPOSAL",
    "SETUP_EXPIRY_FUTURES_MARKET_PROPOSAL",
];

export const msgSubmitProposalSpotMarketLaunchSimiles = [
    "SUBMIT_SPOT_MARKET_PROPOSAL",
    "CREATE_SPOT_MARKET_PROPOSAL",
    "INITIALIZE_SPOT_MARKET_PROPOSAL",
    "START_SPOT_MARKET_PROPOSAL",
    "LAUNCH_SPOT_MARKET_PROPOSAL",
    "PROPOSE_SPOT_MARKET",
    "BEGIN_SPOT_MARKET_PROPOSAL",
    "ESTABLISH_SPOT_MARKET_PROPOSAL",
    "SETUP_SPOT_MARKET_PROPOSAL",
];

export const msgSubmitProposalPerpetualMarketLaunchSimiles = [
    "SUBMIT_PERPETUAL_MARKET_PROPOSAL",
    "CREATE_PERPETUAL_MARKET_PROPOSAL",
    "INITIALIZE_PERPETUAL_MARKET_PROPOSAL",
    "START_PERPETUAL_MARKET_PROPOSAL",
    "LAUNCH_PERPETUAL_MARKET_PROPOSAL",
    "PROPOSE_PERPETUAL_MARKET",
    "BEGIN_PERPETUAL_MARKET_PROPOSAL",
    "ESTABLISH_PERPETUAL_MARKET_PROPOSAL",
    "SETUP_PERPETUAL_MARKET_PROPOSAL",
];

export const msgVoteSimiles = [
    "SUBMIT_VOTE",
    "CAST_VOTE",
    "REGISTER_VOTE",
    "RECORD_VOTE",
    "ENTER_VOTE",
    "PLACE_VOTE",
    "LOG_VOTE",
    "SEND_VOTE",
    "MAKE_VOTE",
];

export const msgSubmitTextProposalSimiles = [
    "SUBMIT_TEXT_PROPOSAL",
    "CREATE_TEXT_PROPOSAL",
    "INITIALIZE_TEXT_PROPOSAL",
    "START_TEXT_PROPOSAL",
    "LAUNCH_TEXT_PROPOSAL",
    "PROPOSE_TEXT_CHANGE",
    "BEGIN_TEXT_PROPOSAL",
    "ESTABLISH_TEXT_PROPOSAL",
    "SETUP_TEXT_PROPOSAL",
];

export const msgSubmitProposalSpotMarketParamUpdateSimiles = [
    "SUBMIT_SPOT_MARKET_PARAM_UPDATE",
    "CREATE_SPOT_MARKET_PARAM_UPDATE",
    "INITIALIZE_SPOT_MARKET_PARAM_UPDATE",
    "START_SPOT_MARKET_PARAM_UPDATE",
    "LAUNCH_SPOT_MARKET_PARAM_UPDATE",
    "PROPOSE_SPOT_MARKET_PARAM_CHANGE",
    "BEGIN_SPOT_MARKET_PARAM_UPDATE",
    "ESTABLISH_SPOT_MARKET_PARAM_UPDATE",
    "SETUP_SPOT_MARKET_PARAM_UPDATE",
];

export const msgSubmitGenericProposalSimiles = [
    "SUBMIT_GENERIC_PROPOSAL",
    "CREATE_GENERIC_PROPOSAL",
    "INITIALIZE_GENERIC_PROPOSAL",
    "START_GENERIC_PROPOSAL",
    "LAUNCH_GENERIC_PROPOSAL",
    "PROPOSE_GENERIC_CHANGE",
    "BEGIN_GENERIC_PROPOSAL",
    "ESTABLISH_GENERIC_PROPOSAL",
    "SETUP_GENERIC_PROPOSAL",
];

export const msgGovDepositSimiles = [
    "SUBMIT_PROPOSAL_DEPOSIT",
    "ADD_PROPOSAL_DEPOSIT",
    "MAKE_PROPOSAL_DEPOSIT",
    "SEND_PROPOSAL_DEPOSIT",
    "PLACE_PROPOSAL_DEPOSIT",
    "TRANSFER_PROPOSAL_DEPOSIT",
    "DEPOSIT_TO_PROPOSAL",
    "FUND_PROPOSAL",
    "CONTRIBUTE_TO_PROPOSAL",
];
