export const getDenomTraceSimiles = [
    "VIEW_DENOM_TRACE",
    "GET_DENOM_TRACE",
    "CHECK_DENOM_TRACE",
    "FETCH_DENOM_TRACE",
    "READ_DENOM_TRACE",
    "DISPLAY_DENOM_TRACE",
    "SHOW_DENOM_TRACE",
    "LIST_DENOM_TRACE",
    "RETRIEVE_DENOM_TRACE",
];

export const getDenomsTraceSimiles = [
    "VIEW_DENOM_TRACES",
    "GET_DENOM_TRACES",
    "CHECK_DENOM_TRACES",
    "FETCH_DENOM_TRACES",
    "READ_DENOM_TRACES",
    "DISPLAY_DENOM_TRACES",
    "SHOW_DENOM_TRACES",
    "LIST_DENOM_TRACES",
    "RETRIEVE_DENOM_TRACES",
];

export const msgIBCTransferSimiles = [
    "SUBMIT_IBC_TRANSFER",
    "EXECUTE_IBC_TRANSFER",
    "PERFORM_IBC_TRANSFER",
    "SEND_IBC_TOKENS",
    "TRANSFER_IBC_TOKENS",
    "INITIATE_IBC_TRANSFER",
    "START_IBC_TRANSFER",
    "CREATE_IBC_TRANSFER",
    "PROCESS_IBC_TRANSFER",
];
