export const getInsuranceModuleParamsSimiles = [
    "VIEW_INSURANCE_MODULE_PARAMS",
    "GET_INSURANCE_MODULE_PARAMS",
    "CHECK_INSURANCE_MODULE_PARAMS",
    "FETCH_INSURANCE_MODULE_PARAMS",
    "READ_INSURANCE_MODULE_PARAMS",
    "DISPLAY_INSURANCE_MODULE_PARAMS",
    "SHOW_INSURANCE_MODULE_PARAMS",
    "LIST_INSURANCE_MODULE_PARAMS",
    "RETRIEVE_INSURANCE_MODULE_PARAMS",
];

export const getInsuranceFundsSimiles = [
    "VIEW_INSURANCE_FUNDS",
    "GET_INSURANCE_FUNDS",
    "CHECK_INSURANCE_FUNDS",
    "FETCH_INSURANCE_FUNDS",
    "READ_INSURANCE_FUNDS",
    "DISPLAY_INSURANCE_FUNDS",
    "SHOW_INSURANCE_FUNDS",
    "LIST_INSURANCE_FUNDS",
    "RETRIEVE_INSURANCE_FUNDS",
];

export const getInsuranceFundSimiles = [
    "VIEW_INSURANCE_FUND",
    "GET_INSURANCE_FUND",
    "CHECK_INSURANCE_FUND",
    "FETCH_INSURANCE_FUND",
    "READ_INSURANCE_FUND",
    "DISPLAY_INSURANCE_FUND",
    "SHOW_INSURANCE_FUND",
    "LIST_INSURANCE_FUND",
    "RETRIEVE_INSURANCE_FUND",
];

export const getEstimatedRedemptionsSimiles = [
    "VIEW_ESTIMATED_REDEMPTIONS",
    "GET_ESTIMATED_REDEMPTIONS",
    "CHECK_ESTIMATED_REDEMPTIONS",
    "FETCH_ESTIMATED_REDEMPTIONS",
    "READ_ESTIMATED_REDEMPTIONS",
    "DISPLAY_ESTIMATED_REDEMPTIONS",
    "SHOW_ESTIMATED_REDEMPTIONS",
    "LIST_ESTIMATED_REDEMPTIONS",
    "RETRIEVE_ESTIMATED_REDEMPTIONS",
];

export const getPendingRedemptionsSimiles = [
    "VIEW_PENDING_REDEMPTIONS",
    "GET_PENDING_REDEMPTIONS",
    "CHECK_PENDING_REDEMPTIONS",
    "FETCH_PENDING_REDEMPTIONS",
    "READ_PENDING_REDEMPTIONS",
    "DISPLAY_PENDING_REDEMPTIONS",
    "SHOW_PENDING_REDEMPTIONS",
    "LIST_PENDING_REDEMPTIONS",
    "RETRIEVE_PENDING_REDEMPTIONS",
];

export const msgCreateInsuranceFundSimiles = [
    "CREATE_INSURANCE_FUND",
    "ESTABLISH_INSURANCE_FUND",
    "SETUP_INSURANCE_FUND",
    "INITIALIZE_INSURANCE_FUND",
    "START_INSURANCE_FUND",
    "LAUNCH_INSURANCE_FUND",
    "OPEN_INSURANCE_FUND",
    "BEGIN_INSURANCE_FUND",
    "INSTITUTE_INSURANCE_FUND",
];

export const msgRequestRedemptionSimiles = [
    "REQUEST_REDEMPTION",
    "INITIATE_REDEMPTION",
    "SUBMIT_REDEMPTION",
    "START_REDEMPTION",
    "PROCESS_REDEMPTION",
    "CREATE_REDEMPTION",
    "EXECUTE_REDEMPTION",
    "BEGIN_REDEMPTION",
    "PERFORM_REDEMPTION",
];

export const msgUnderwriteSimiles = [
    "UNDERWRITE_INSURANCE",
    "BACK_INSURANCE",
    "SUPPORT_INSURANCE",
    "GUARANTEE_INSURANCE",
    "SECURE_INSURANCE",
    "SPONSOR_INSURANCE",
    "FUND_INSURANCE",
    "FINANCE_INSURANCE",
    "PROVIDE_INSURANCE_BACKING",
];
