export const getMintModuleParamsSimiles = [
    "VIEW_MINT_MODULE_PARAMS",
    "GET_MINT_MODULE_PARAMS",
    "CHECK_MINT_MODULE_PARAMS",
    "FETCH_MINT_MODULE_PARAMS",
    "READ_MINT_MODULE_PARAMS",
    "DISPLAY_MINT_MODULE_PARAMS",
    "SHOW_MINT_MODULE_PARAMS",
    "LIST_MINT_MODULE_PARAMS",
    "RETRIEVE_MINT_MODULE_PARAMS",
];

export const getInflationSimiles = [
    "VIEW_INFLATION_RATE",
    "GET_INFLATION_RATE",
    "CHECK_INFLATION_RATE",
    "FETCH_INFLATION_RATE",
    "READ_INFLATION_RATE",
    "DISPLAY_INFLATION_RATE",
    "SHOW_INFLATION_RATE",
    "LIST_INFLATION_RATE",
    "RETRIEVE_INFLATION_RATE",
];

export const getAnnualProvisionsSimiles = [
    "VIEW_ANNUAL_PROVISIONS",
    "GET_ANNUAL_PROVISIONS",
    "CHECK_ANNUAL_PROVISIONS",
    "FETCH_ANNUAL_PROVISIONS",
    "READ_ANNUAL_PROVISIONS",
    "DISPLAY_ANNUAL_PROVISIONS",
    "SHOW_ANNUAL_PROVISIONS",
    "LIST_ANNUAL_PROVISIONS",
    "RETRIEVE_ANNUAL_PROVISIONS",
];
