// Vault Related Similes
export const getVaultSimiles = [
    "VIEW_VAULT",
    "GET_VAULT",
    "CHECK_VAULT",
    "FETCH_VAULT",
    "READ_VAULT",
    "DISPLAY_VAULT",
    "SHOW_VAULT",
    "LIST_VAULT",
    "RETRIEVE_VAULT",
];

export const getVaultsSimiles = [
    "VIEW_VAULTS",
    "GET_VAULTS",
    "CHECK_VAULTS",
    "FETCH_VAULTS",
    "READ_VAULTS",
    "DISPLAY_VAULTS",
    "SHOW_VAULTS",
    "LIST_VAULTS",
    "RETRIEVE_VAULTS",
];

export const getVaultsByHolderAddressSimiles = [
    "VIEW_HOLDER_VAULTS",
    "GET_HOLDER_VAULTS",
    "CHECK_HOLDER_VAULTS",
    "FETCH_HOLDER_VAULTS",
    "READ_HOLDER_VAULTS",
    "DISPLAY_HOLDER_VAULTS",
    "SHOW_HOLDER_VAULTS",
    "LIST_HOLDER_VAULTS",
    "RETRIEVE_HOLDER_VAULTS",
];

// LP Token Related Similes
export const getLpTokenPriceChartSimiles = [
    "VIEW_LP_PRICE_CHART",
    "GET_LP_PRICE_CHART",
    "CHECK_LP_PRICE_CHART",
    "FETCH_LP_PRICE_CHART",
    "READ_LP_PRICE_CHART",
    "DISPLAY_LP_PRICE_CHART",
    "SHOW_LP_PRICE_CHART",
    "LIST_LP_PRICE_CHART",
    "RETRIEVE_LP_PRICE_CHART",
];

export const getLPHoldersSimiles = [
    "VIEW_LP_HOLDERS",
    "GET_LP_HOLDERS",
    "CHECK_LP_HOLDERS",
    "FETCH_LP_HOLDERS",
    "READ_LP_HOLDERS",
    "DISPLAY_LP_HOLDERS",
    "SHOW_LP_HOLDERS",
    "LIST_LP_HOLDERS",
    "RETRIEVE_LP_HOLDERS",
];

// TVL and Portfolio Related Similes
export const getTVLChartSimiles = [
    "VIEW_TVL_CHART",
    "GET_TVL_CHART",
    "CHECK_TVL_CHART",
    "FETCH_TVL_CHART",
    "READ_TVL_CHART",
    "DISPLAY_TVL_CHART",
    "SHOW_TVL_CHART",
    "LIST_TVL_CHART",
    "RETRIEVE_TVL_CHART",
];

export const getHolderPortfolioSimiles = [
    "VIEW_HOLDER_PORTFOLIO",
    "GET_HOLDER_PORTFOLIO",
    "CHECK_HOLDER_PORTFOLIO",
    "FETCH_HOLDER_PORTFOLIO",
    "READ_HOLDER_PORTFOLIO",
    "DISPLAY_HOLDER_PORTFOLIO",
    "SHOW_HOLDER_PORTFOLIO",
    "LIST_HOLDER_PORTFOLIO",
    "RETRIEVE_HOLDER_PORTFOLIO",
];

// MITO_LEADERBOARD Related Similes
export const getLeaderboardSimiles = [
    "VIEW_MITO_LEADERBOARD",
    "GET_MITO_LEADERBOARD",
    "CHECK_MITO_LEADERBOARD",
    "FETCH_MITO_LEADERBOARD",
    "READ_MITO_LEADERBOARD",
    "DISPLAY_MITO_LEADERBOARD",
    "SHOW_MITO_LEADERBOARD",
    "LIST_MITO_LEADERBOARD",
    "RETRIEVE_MITO_LEADERBOARD",
];

export const getLeaderboardEpochsSimiles = [
    "VIEW_MITO_LEADERBOARD_EPOCHS",
    "GET_MITO_LEADERBOARD_EPOCHS",
    "CHECK_MITO_LEADERBOARD_EPOCHS",
    "FETCH_MITO_LEADERBOARD_EPOCHS",
    "READ_MITO_LEADERBOARD_EPOCHS",
    "DISPLAY_MITO_LEADERBOARD_EPOCHS",
    "SHOW_MITO_LEADERBOARD_EPOCHS",
    "LIST_MITO_LEADERBOARD_EPOCHS",
    "RETRIEVE_MITO_LEADERBOARD_EPOCHS",
];

// Transfer Related Similes
export const getTransferHistorySimiles = [
    "VIEW_TRANSFER_HISTORY",
    "GET_TRANSFER_HISTORY",
    "CHECK_TRANSFER_HISTORY",
    "FETCH_TRANSFER_HISTORY",
    "READ_TRANSFER_HISTORY",
    "DISPLAY_TRANSFER_HISTORY",
    "SHOW_TRANSFER_HISTORY",
    "LIST_TRANSFER_HISTORY",
    "RETRIEVE_TRANSFER_HISTORY",
];

// Staking Related Similes
export const getStakingPoolsSimiles = [
    "VIEW_STAKING_POOLS",
    "GET_STAKING_POOLS",
    "CHECK_STAKING_POOLS",
    "FETCH_STAKING_POOLS",
    "READ_STAKING_POOLS",
    "DISPLAY_STAKING_POOLS",
    "SHOW_STAKING_POOLS",
    "LIST_STAKING_POOLS",
    "RETRIEVE_STAKING_POOLS",
];

export const getStakingHistorySimiles = [
    "VIEW_STAKING_HISTORY",
    "GET_STAKING_HISTORY",
    "CHECK_STAKING_HISTORY",
    "FETCH_STAKING_HISTORY",
    "READ_STAKING_HISTORY",
    "DISPLAY_STAKING_HISTORY",
    "SHOW_STAKING_HISTORY",
    "LIST_STAKING_HISTORY",
    "RETRIEVE_STAKING_HISTORY",
];

export const getStakingRewardsByAccountSimiles = [
    "VIEW_STAKING_REWARDS",
    "GET_STAKING_REWARDS",
    "CHECK_STAKING_REWARDS",
    "FETCH_STAKING_REWARDS",
    "READ_STAKING_REWARDS",
    "DISPLAY_STAKING_REWARDS",
    "SHOW_STAKING_REWARDS",
    "LIST_STAKING_REWARDS",
    "RETRIEVE_STAKING_REWARDS",
];

// Mission Related Similes
export const getMissionsSimiles = [
    "VIEW_MISSIONS",
    "GET_MISSIONS",
    "CHECK_MISSIONS",
    "FETCH_MISSIONS",
    "READ_MISSIONS",
    "DISPLAY_MISSIONS",
    "SHOW_MISSIONS",
    "LIST_MISSIONS",
    "RETRIEVE_MISSIONS",
];

export const getMissionLeaderboardSimiles = [
    "VIEW_MISSION_MITO_LEADERBOARD",
    "GET_MISSION_MITO_LEADERBOARD",
    "CHECK_MISSION_MITO_LEADERBOARD",
    "FETCH_MISSION_MITO_LEADERBOARD",
    "READ_MISSION_MITO_LEADERBOARD",
    "DISPLAY_MISSION_MITO_LEADERBOARD",
    "SHOW_MISSION_MITO_LEADERBOARD",
    "LIST_MISSION_MITO_LEADERBOARD",
    "RETRIEVE_MISSION_MITO_LEADERBOARD",
];

// IDO Related Similes
export const getIDOSimiles = [
    "VIEW_IDO",
    "GET_IDO",
    "CHECK_IDO",
    "FETCH_IDO",
    "READ_IDO",
    "DISPLAY_IDO",
    "SHOW_IDO",
    "LIST_IDO",
    "RETRIEVE_IDO",
];

export const getIDOsSimiles = [
    "VIEW_IDOS",
    "GET_IDOS",
    "CHECK_IDOS",
    "FETCH_IDOS",
    "READ_IDOS",
    "DISPLAY_IDOS",
    "SHOW_IDOS",
    "LIST_IDOS",
    "RETRIEVE_IDOS",
];

export const getIDOSubscribersSimiles = [
    "VIEW_IDO_SUBSCRIBERS",
    "GET_IDO_SUBSCRIBERS",
    "CHECK_IDO_SUBSCRIBERS",
    "FETCH_IDO_SUBSCRIBERS",
    "READ_IDO_SUBSCRIBERS",
    "DISPLAY_IDO_SUBSCRIBERS",
    "SHOW_IDO_SUBSCRIBERS",
    "LIST_IDO_SUBSCRIBERS",
    "RETRIEVE_IDO_SUBSCRIBERS",
];

export const getIDOSubscriptionSimiles = [
    "VIEW_IDO_SUBSCRIPTION",
    "GET_IDO_SUBSCRIPTION",
    "CHECK_IDO_SUBSCRIPTION",
    "FETCH_IDO_SUBSCRIPTION",
    "READ_IDO_SUBSCRIPTION",
    "DISPLAY_IDO_SUBSCRIPTION",
    "SHOW_IDO_SUBSCRIPTION",
    "LIST_IDO_SUBSCRIPTION",
    "RETRIEVE_IDO_SUBSCRIPTION",
];

export const getIDOActivitiesSimiles = [
    "VIEW_IDO_ACTIVITIES",
    "GET_IDO_ACTIVITIES",
    "CHECK_IDO_ACTIVITIES",
    "FETCH_IDO_ACTIVITIES",
    "READ_IDO_ACTIVITIES",
    "DISPLAY_IDO_ACTIVITIES",
    "SHOW_IDO_ACTIVITIES",
    "LIST_IDO_ACTIVITIES",
    "RETRIEVE_IDO_ACTIVITIES",
];

export const getIDOWhitelistSimiles = [
    "VIEW_IDO_WHITELIST",
    "GET_IDO_WHITELIST",
    "CHECK_IDO_WHITELIST",
    "FETCH_IDO_WHITELIST",
    "READ_IDO_WHITELIST",
    "DISPLAY_IDO_WHITELIST",
    "SHOW_IDO_WHITELIST",
    "LIST_IDO_WHITELIST",
    "RETRIEVE_IDO_WHITELIST",
];

export const getClaimReferencesSimiles = [
    "VIEW_CLAIM_REFERENCES",
    "GET_CLAIM_REFERENCES",
    "CHECK_CLAIM_REFERENCES",
    "FETCH_CLAIM_REFERENCES",
    "READ_CLAIM_REFERENCES",
    "DISPLAY_CLAIM_REFERENCES",
    "SHOW_CLAIM_REFERENCES",
    "LIST_CLAIM_REFERENCES",
    "RETRIEVE_CLAIM_REFERENCES",
];

// Mito interactions

// Launchpad Related Similes
export const getLaunchpadSubscribeSimiles = [
    "LAUNCHPAD_SUBSCRIBE",
    "JOIN_LAUNCHPAD",
    "ENTER_LAUNCHPAD",
    "PARTICIPATE_LAUNCHPAD",
    "REGISTER_LAUNCHPAD",
    "ENROLL_LAUNCHPAD",
    "ACCESS_LAUNCHPAD",
    "ENGAGE_LAUNCHPAD",
    "START_LAUNCHPAD",
];

export const getLaunchpadClaimSimiles = [
    "LAUNCHPAD_CLAIM",
    "COLLECT_LAUNCHPAD",
    "WITHDRAW_LAUNCHPAD",
    "RETRIEVE_LAUNCHPAD",
    "REDEEM_LAUNCHPAD",
    "GATHER_LAUNCHPAD",
    "OBTAIN_LAUNCHPAD",
    "ACQUIRE_LAUNCHPAD",
    "EXTRACT_LAUNCHPAD",
];

// Vault Related Action Similes
export const getSubscribeVaultSimiles = [
    "SUBSCRIBE_VAULT",
    "JOIN_VAULT",
    "ENTER_VAULT",
    "PARTICIPATE_VAULT",
    "REGISTER_VAULT",
    "ENROLL_VAULT",
    "ACCESS_VAULT",
    "ENGAGE_VAULT",
    "START_VAULT",
];

export const getInstantiateCPMMVaultSimiles = [
    "INSTANTIATE_CPMM_VAULT",
    "CREATE_CPMM_VAULT",
    "DEPLOY_CPMM_VAULT",
    "LAUNCH_CPMM_VAULT",
    "INITIALIZE_CPMM_VAULT",
    "SETUP_CPMM_VAULT",
    "START_CPMM_VAULT",
    "BEGIN_CPMM_VAULT",
    "ESTABLISH_CPMM_VAULT",
];
export const getRedeemFromVaultSimiles = [
    "WITHDRAW_FROM_VAULT",
    "EXIT_VAULT",
    "REDEEM_FROM_VAULT",
    "REMOVE_FROM_VAULT",
    "LEAVE_VAULT",
    "CASH_OUT_VAULT",
    "EXTRACT_FROM_VAULT",
    "PULL_FROM_VAULT",
    "RECOVER_FROM_VAULT",
];

export const getStakeVaultLPSimiles = [
    "LOCK_VAULT_LP",
    "STAKE_VAULT_LP",
    "COMMIT_VAULT_LP",
    "BOND_VAULT_LP",
    "ALLOCATE_VAULT_LP",
    "INVEST_VAULT_LP",
    "HOLD_VAULT_LP",
];

export const getUnstakeVaultLPSimiles = [
    "UNLOCK_VAULT_LP",
    "UNSTAKE_VAULT_LP",
    "RELEASE_VAULT_LP",
    "UNBOND_VAULT_LP",
    "FREE_VAULT_LP",
];

export const getClaimVaultRewardsSimiles = [
    "COLLECT_VAULT_REWARDS",
    "HARVEST_VAULT_REWARDS",
    "CLAIM_VAULT_REWARDS",
    "GATHER_VAULT_REWARDS",
    "RECEIVE_VAULT_REWARDS",
    "WITHDRAW_VAULT_REWARDS",
    "GET_VAULT_REWARDS",
    "FETCH_VAULT_REWARDS",
    "REDEEM_VAULT_REWARDS",
];
