export const getPeggyModuleParamsSimiles = [
    "VIEW_PEGGY_BRIDGE_PARAMS",
    "GET_PEGGY_BRIDGE_PARAMS",
    "CHECK_PEGGY_BRIDGE_PARAMS",
    "FETCH_PEGGY_BRIDGE_PARAMS",
    "READ_PEGGY_BRIDGE_PARAMS",
    "DISPLAY_PEGGY_BRIDGE_PARAMS",
    "SHOW_PEGGY_BRIDGE_PARAMS",
    "LIST_PEGGY_BRIDGE_PARAMS",
    "RETRIEVE_PEGGY_BRIDGE_PARAMS",
];

export const msgSendToEthSimiles = [
    "SEND_TO_ETHEREUM",
    "TRANSFER_TO_ETH",
    "BRIDGE_TO_ETHEREUM",
    "MOVE_TO_ETH",
    "TRANSMIT_TO_ETHEREUM",
    "FORWARD_TO_ETH",
    "RELAY_TO_ETHEREUM",
    "DISPATCH_TO_ETH",
    "TRANSPORT_TO_ETHEREUM",
];
