export const getAddressesByRoleSimiles = [
    "VIEW_ROLE_ADDRESSES",
    "GET_ROLE_ADDRESSES",
    "CHECK_ROLE_ADDRESSES",
    "FETCH_ROLE_ADDRESSES",
    "READ_ROLE_ADDRESSES",
    "DISPLAY_ROLE_ADDRESSES",
    "SHOW_ROLE_ADDRESSES",
    "LIST_ROLE_ADDRESSES",
    "RETRIEVE_ROLE_ADDRESSES",
];

export const getAddressRolesSimiles = [
    "VIEW_ADDRESS_ROLES",
    "GET_ADDRESS_ROLES",
    "CHECK_ADDRESS_ROLES",
    "FETCH_ADDRESS_ROLES",
    "READ_ADDRESS_ROLES",
    "DISPLAY_ADDRESS_ROLES",
    "SHOW_ADDRESS_ROLES",
    "LIST_ADDRESS_ROLES",
    "RETRIEVE_ADDRESS_ROLES",
];

export const getAllNamespacesSimiles = [
    "VIEW_NAMESPACES",
    "GET_NAMESPACES",
    "CHECK_NAMESPACES",
    "FETCH_NAMESPACES",
    "READ_NAMESPACES",
    "DISPLAY_NAMESPACES",
    "SHOW_NAMESPACES",
    "LIST_NAMESPACES",
    "RETRIEVE_NAMESPACES",
];

export const getPermissionsModuleParamsSimiles = [
    "VIEW_PERMISSIONS_PARAMS",
    "GET_PERMISSIONS_PARAMS",
    "CHECK_PERMISSIONS_PARAMS",
    "FETCH_PERMISSIONS_PARAMS",
    "READ_PERMISSIONS_PARAMS",
    "DISPLAY_PERMISSIONS_PARAMS",
    "SHOW_PERMISSIONS_PARAMS",
    "LIST_PERMISSIONS_PARAMS",
    "RETRIEVE_PERMISSIONS_PARAMS",
];

export const getNamespaceByDenomSimiles = [
    "VIEW_DENOM_NAMESPACE",
    "GET_DENOM_NAMESPACE",
    "CHECK_DENOM_NAMESPACE",
    "FETCH_DENOM_NAMESPACE",
    "READ_DENOM_NAMESPACE",
    "DISPLAY_DENOM_NAMESPACE",
    "SHOW_DENOM_NAMESPACE",
    "LIST_DENOM_NAMESPACE",
    "RETRIEVE_DENOM_NAMESPACE",
];

export const getVouchersForAddressSimiles = [
    "VIEW_ADDRESS_VOUCHERS",
    "GET_ADDRESS_VOUCHERS",
    "CHECK_ADDRESS_VOUCHERS",
    "FETCH_ADDRESS_VOUCHERS",
    "READ_ADDRESS_VOUCHERS",
    "DISPLAY_ADDRESS_VOUCHERS",
    "SHOW_ADDRESS_VOUCHERS",
    "LIST_ADDRESS_VOUCHERS",
    "RETRIEVE_ADDRESS_VOUCHERS",
];
