// Module and Pool Query Actions
export const getStakingModuleParamsSimiles = [
    "VIEW_STAKING_PARAMS",
    "GET_STAKING_PARAMS",
    "CHECK_STAKING_PARAMS",
    "FETCH_STAKING_PARAMS",
    "READ_STAKING_PARAMS",
    "DISPLAY_STAKING_PARAMS",
    "SHOW_STAKING_PARAMS",
    "LIST_STAKING_PARAMS",
    "RETRIEVE_STAKING_PARAMS",
];

export const getPoolSimiles = [
    "VIEW_STAKING_POOL",
    "GET_STAKING_POOL",
    "CHECK_STAKING_POOL",
    "FETCH_STAKING_POOL",
    "READ_STAKING_POOL",
    "DISPLAY_STAKING_POOL",
    "SHOW_STAKING_POOL",
    "LIST_STAKING_POOL",
    "RETRIEVE_STAKING_POOL",
];

// Validator Query Actions
export const getValidatorsSimiles = [
    "VIEW_VALIDATORS",
    "GET_VALIDATORS",
    "CHECK_VALIDATORS",
    "FETCH_VALIDATORS",
    "READ_VALIDATORS",
    "DISPLAY_VALIDATORS",
    "SHOW_VALIDATORS",
    "LIST_VALIDATORS",
    "RETRIEVE_VALIDATORS",
];

export const getValidatorSimiles = [
    "VIEW_VALIDATOR",
    "GET_VALIDATOR",
    "CHECK_VALIDATOR",
    "FETCH_VALIDATOR",
    "READ_VALIDATOR",
    "DISPLAY_VALIDATOR",
    "SHOW_VALIDATOR",
    "LIST_VALIDATOR",
    "RETRIEVE_VALIDATOR",
];

// Delegation Query Actions
export const getValidatorDelegationsSimiles = [
    "VIEW_VALIDATOR_DELEGATIONS",
    "GET_VALIDATOR_DELEGATIONS",
    "CHECK_VALIDATOR_DELEGATIONS",
    "FETCH_VALIDATOR_DELEGATIONS",
    "READ_VALIDATOR_DELEGATIONS",
    "DISPLAY_VALIDATOR_DELEGATIONS",
    "SHOW_VALIDATOR_DELEGATIONS",
    "LIST_VALIDATOR_DELEGATIONS",
    "RETRIEVE_VALIDATOR_DELEGATIONS",
];

export const getValidatorDelegationsNoThrowSimiles = [
    "VIEW_VALIDATOR_DELEGATIONS_SAFE",
    "GET_VALIDATOR_DELEGATIONS_SAFE",
    "CHECK_VALIDATOR_DELEGATIONS_SAFE",
    "FETCH_VALIDATOR_DELEGATIONS_SAFE",
    "READ_VALIDATOR_DELEGATIONS_SAFE",
    "DISPLAY_VALIDATOR_DELEGATIONS_SAFE",
    "SHOW_VALIDATOR_DELEGATIONS_SAFE",
    "LIST_VALIDATOR_DELEGATIONS_SAFE",
    "RETRIEVE_VALIDATOR_DELEGATIONS_SAFE",
];

export const getValidatorUnbondingDelegationsSimiles = [
    "VIEW_VALIDATOR_UNBONDING",
    "GET_VALIDATOR_UNBONDING",
    "CHECK_VALIDATOR_UNBONDING",
    "FETCH_VALIDATOR_UNBONDING",
    "READ_VALIDATOR_UNBONDING",
    "DISPLAY_VALIDATOR_UNBONDING",
    "SHOW_VALIDATOR_UNBONDING",
    "LIST_VALIDATOR_UNBONDING",
    "RETRIEVE_VALIDATOR_UNBONDING",
];

export const getValidatorUnbondingDelegationsNoThrowSimiles = [
    "VIEW_VALIDATOR_UNBONDING_SAFE",
    "GET_VALIDATOR_UNBONDING_SAFE",
    "CHECK_VALIDATOR_UNBONDING_SAFE",
    "FETCH_VALIDATOR_UNBONDING_SAFE",
    "READ_VALIDATOR_UNBONDING_SAFE",
    "DISPLAY_VALIDATOR_UNBONDING_SAFE",
    "SHOW_VALIDATOR_UNBONDING_SAFE",
    "LIST_VALIDATOR_UNBONDING_SAFE",
    "RETRIEVE_VALIDATOR_UNBONDING_SAFE",
];

export const getDelegationSimiles = [
    "VIEW_DELEGATION",
    "GET_DELEGATION",
    "CHECK_DELEGATION",
    "FETCH_DELEGATION",
    "READ_DELEGATION",
    "DISPLAY_DELEGATION",
    "SHOW_DELEGATION",
    "LIST_DELEGATION",
    "RETRIEVE_DELEGATION",
];

export const getDelegationsSimiles = [
    "VIEW_DELEGATIONS",
    "GET_DELEGATIONS",
    "CHECK_DELEGATIONS",
    "FETCH_DELEGATIONS",
    "READ_DELEGATIONS",
    "DISPLAY_DELEGATIONS",
    "SHOW_DELEGATIONS",
    "LIST_DELEGATIONS",
    "RETRIEVE_DELEGATIONS",
];

export const getDelegationsNoThrowSimiles = [
    "VIEW_DELEGATIONS_SAFE",
    "GET_DELEGATIONS_SAFE",
    "CHECK_DELEGATIONS_SAFE",
    "FETCH_DELEGATIONS_SAFE",
    "READ_DELEGATIONS_SAFE",
    "DISPLAY_DELEGATIONS_SAFE",
    "SHOW_DELEGATIONS_SAFE",
    "LIST_DELEGATIONS_SAFE",
    "RETRIEVE_DELEGATIONS_SAFE",
];

export const getDelegatorsSimiles = [
    "VIEW_DELEGATORS",
    "GET_DELEGATORS",
    "CHECK_DELEGATORS",
    "FETCH_DELEGATORS",
    "READ_DELEGATORS",
    "DISPLAY_DELEGATORS",
    "SHOW_DELEGATORS",
    "LIST_DELEGATORS",
    "RETRIEVE_DELEGATORS",
];

export const getDelegatorsNoThrowSimiles = [
    "VIEW_DELEGATORS_SAFE",
    "GET_DELEGATORS_SAFE",
    "CHECK_DELEGATORS_SAFE",
    "FETCH_DELEGATORS_SAFE",
    "READ_DELEGATORS_SAFE",
    "DISPLAY_DELEGATORS_SAFE",
    "SHOW_DELEGATORS_SAFE",
    "LIST_DELEGATORS_SAFE",
    "RETRIEVE_DELEGATORS_SAFE",
];

export const getUnbondingDelegationsSimiles = [
    "VIEW_UNBONDING_DELEGATIONS",
    "GET_UNBONDING_DELEGATIONS",
    "CHECK_UNBONDING_DELEGATIONS",
    "FETCH_UNBONDING_DELEGATIONS",
    "READ_UNBONDING_DELEGATIONS",
    "DISPLAY_UNBONDING_DELEGATIONS",
    "SHOW_UNBONDING_DELEGATIONS",
    "LIST_UNBONDING_DELEGATIONS",
    "RETRIEVE_UNBONDING_DELEGATIONS",
];

export const getUnbondingDelegationsNoThrowSimiles = [
    "VIEW_UNBONDING_DELEGATIONS_SAFE",
    "GET_UNBONDING_DELEGATIONS_SAFE",
    "CHECK_UNBONDING_DELEGATIONS_SAFE",
    "FETCH_UNBONDING_DELEGATIONS_SAFE",
    "READ_UNBONDING_DELEGATIONS_SAFE",
    "DISPLAY_UNBONDING_DELEGATIONS_SAFE",
    "SHOW_UNBONDING_DELEGATIONS_SAFE",
    "LIST_UNBONDING_DELEGATIONS_SAFE",
    "RETRIEVE_UNBONDING_DELEGATIONS_SAFE",
];

export const getReDelegationsSimiles = [
    "VIEW_REDELEGATIONS",
    "GET_REDELEGATIONS",
    "CHECK_REDELEGATIONS",
    "FETCH_REDELEGATIONS",
    "READ_REDELEGATIONS",
    "DISPLAY_REDELEGATIONS",
    "SHOW_REDELEGATIONS",
    "LIST_REDELEGATIONS",
    "RETRIEVE_REDELEGATIONS",
];

export const getReDelegationsNoThrowSimiles = [
    "VIEW_REDELEGATIONS_SAFE",
    "GET_REDELEGATIONS_SAFE",
    "CHECK_REDELEGATIONS_SAFE",
    "FETCH_REDELEGATIONS_SAFE",
    "READ_REDELEGATIONS_SAFE",
    "DISPLAY_REDELEGATIONS_SAFE",
    "SHOW_REDELEGATIONS_SAFE",
    "LIST_REDELEGATIONS_SAFE",
    "RETRIEVE_REDELEGATIONS_SAFE",
];

// Message Actions
export const msgBeginRedelegateSimiles = [
    "START_REDELEGATION",
    "BEGIN_REDELEGATION",
    "INITIATE_REDELEGATION",
    "CREATE_REDELEGATION",
    "SUBMIT_REDELEGATION",
    "EXECUTE_REDELEGATION",
    "PROCESS_REDELEGATION",
    "PERFORM_REDELEGATION",
    "LAUNCH_REDELEGATION",
];

export const msgDelegateSimiles = [
    "START_DELEGATION",
    "BEGIN_DELEGATION",
    "INITIATE_DELEGATION",
    "CREATE_DELEGATION",
    "SUBMIT_DELEGATION",
    "EXECUTE_DELEGATION",
    "PROCESS_DELEGATION",
    "PERFORM_DELEGATION",
    "LAUNCH_DELEGATION",
];

export const msgUndelegateSimiles = [
    "START_UNDELEGATION",
    "BEGIN_UNDELEGATION",
    "INITIATE_UNDELEGATION",
    "CREATE_UNDELEGATION",
    "SUBMIT_UNDELEGATION",
    "EXECUTE_UNDELEGATION",
    "PROCESS_UNDELEGATION",
    "PERFORM_UNDELEGATION",
    "LAUNCH_UNDELEGATION",
];

export const msgCreateValidatorSimiles = [
    "CREATE_VALIDATOR",
    "ESTABLISH_VALIDATOR",
    "INITIALIZE_VALIDATOR",
    "SETUP_VALIDATOR",
    "REGISTER_VALIDATOR",
    "START_VALIDATOR",
    "LAUNCH_VALIDATOR",
    "DEPLOY_VALIDATOR",
    "INSTITUTE_VALIDATOR",
];

export const msgEditValidatorSimiles = [
    "UPDATE_VALIDATOR",
    "MODIFY_VALIDATOR",
    "CHANGE_VALIDATOR",
    "EDIT_VALIDATOR",
    "REVISE_VALIDATOR",
    "ALTER_VALIDATOR",
    "ADJUST_VALIDATOR",
    "AMEND_VALIDATOR",
    "TRANSFORM_VALIDATOR",
];

export const msgCancelUnbondingDelegationSimiles = [
    "CANCEL_UNBONDING",
    "STOP_UNBONDING",
    "HALT_UNBONDING",
    "TERMINATE_UNBONDING",
    "END_UNBONDING",
    "ABORT_UNBONDING",
    "WITHDRAW_UNBONDING",
    "REVERSE_UNBONDING",
    "NULLIFY_UNBONDING",
];
