// Query Actions
export const getDenomsFromCreatorSimiles = [
    "VIEW_CREATOR_TOKENS",
    "GET_CREATOR_TOKENS",
    "CHECK_CREATOR_TOKENS",
    "FETCH_CREATOR_TOKENS",
    "READ_CREATOR_TOKENS",
    "DISPLAY_CREATOR_TOKENS",
    "SHOW_CREATOR_TOKENS",
    "LIST_CREATOR_TOKENS",
    "RETRIEVE_CREATOR_TOKENS",
];

export const getDenomAuthorityMetadataSimiles = [
    "VIEW_TOKEN_AUTHORITY",
    "GET_TOKEN_AUTHORITY",
    "CHECK_TOKEN_AUTHORITY",
    "FETCH_TOKEN_AUTHORITY",
    "READ_TOKEN_AUTHORITY",
    "DISPLAY_TOKEN_AUTHORITY",
    "SHOW_TOKEN_AUTHORITY",
    "LIST_TOKEN_AUTHORITY",
    "RETRIEVE_TOKEN_AUTHORITY",
];

export const getTokenFactoryModuleParamsSimiles = [
    "VIEW_TOKEN_FACTORY_PARAMS",
    "GET_TOKEN_FACTORY_PARAMS",
    "CHECK_TOKEN_FACTORY_PARAMS",
    "FETCH_TOKEN_FACTORY_PARAMS",
    "READ_TOKEN_FACTORY_PARAMS",
    "DISPLAY_TOKEN_FACTORY_PARAMS",
    "SHOW_TOKEN_FACTORY_PARAMS",
    "LIST_TOKEN_FACTORY_PARAMS",
    "RETRIEVE_TOKEN_FACTORY_PARAMS",
];

export const getTokenFactoryModuleStateSimiles = [
    "VIEW_TOKEN_FACTORY_STATE",
    "GET_TOKEN_FACTORY_STATE",
    "CHECK_TOKEN_FACTORY_STATE",
    "FETCH_TOKEN_FACTORY_STATE",
    "READ_TOKEN_FACTORY_STATE",
    "DISPLAY_TOKEN_FACTORY_STATE",
    "SHOW_TOKEN_FACTORY_STATE",
    "LIST_TOKEN_FACTORY_STATE",
    "RETRIEVE_TOKEN_FACTORY_STATE",
];

// Message Actions
export const msgBurnSimiles = [
    "BURN_TOKENS",
    "DESTROY_TOKENS",
    "REMOVE_TOKENS",
    "DELETE_TOKENS",
    "ELIMINATE_TOKENS",
    "CONSUME_TOKENS",
    "ERASE_TOKENS",
    "CANCEL_TOKENS",
    "NULLIFY_TOKENS",
];

export const msgChangeAdminSimiles = [
    "UPDATE_TOKEN_ADMIN",
    "CHANGE_TOKEN_ADMIN",
    "MODIFY_TOKEN_ADMIN",
    "TRANSFER_TOKEN_ADMIN",
    "REPLACE_TOKEN_ADMIN",
    "REASSIGN_TOKEN_ADMIN",
    "SWITCH_TOKEN_ADMIN",
    "ALTER_TOKEN_ADMIN",
    "REVISE_TOKEN_ADMIN",
];

export const msgCreateDenomSimiles = [
    "CREATE_TOKEN_DENOM",
    "ESTABLISH_TOKEN_DENOM",
    "INITIALIZE_TOKEN_DENOM",
    "SETUP_TOKEN_DENOM",
    "GENERATE_TOKEN_DENOM",
    "LAUNCH_TOKEN_DENOM",
    "DEPLOY_TOKEN_DENOM",
    "INSTITUTE_TOKEN_DENOM",
    "PRODUCE_TOKEN_DENOM",
];

export const msgMintSimiles = [
    "MINT_TOKENS",
    "ISSUE_TOKENS",
    "GENERATE_TOKENS",
    "CREATE_TOKENS",
    "PRODUCE_TOKENS",
    "MAKE_TOKENS",
    "FORGE_TOKENS",
    "FABRICATE_TOKENS",
    "CONSTRUCT_TOKENS",
];

export const msgSetDenomMetadataSimiles = [
    "UPDATE_TOKEN_METADATA",
    "SET_TOKEN_METADATA",
    "MODIFY_TOKEN_METADATA",
    "CHANGE_TOKEN_METADATA",
    "REVISE_TOKEN_METADATA",
    "ALTER_TOKEN_METADATA",
    "ADJUST_TOKEN_METADATA",
    "EDIT_TOKEN_METADATA",
    "CONFIGURE_TOKEN_METADATA",
];
