// Contract Query Actions
export const getContractAccountsBalanceSimiles = [
    "VIEW_CONTRACT_BALANCES",
    "GET_CONTRACT_BALANCES",
    "CHECK_CONTRACT_BALANCES",
    "FETCH_CONTRACT_BALANCES",
    "READ_CONTRACT_BALANCES",
    "DISPLAY_CONTRACT_BALANCES",
    "SHOW_CONTRACT_BALANCES",
    "LIST_CONTRACT_BALANCES",
    "RETRIEVE_CONTRACT_BALANCES",
];

export const getContractStateSimiles = [
    "VIEW_CONTRACT_STATE",
    "GET_CONTRACT_STATE",
    "CHECK_CONTRACT_STATE",
    "FETCH_CONTRACT_STATE",
    "READ_CONTRACT_STATE",
    "DISPLAY_CONTRACT_STATE",
    "SHOW_CONTRACT_STATE",
    "LIST_CONTRACT_STATE",
    "RETRIEVE_CONTRACT_STATE",
];

export const getContractInfoSimiles = [
    "VIEW_CONTRACT_INFO",
    "GET_CONTRACT_INFO",
    "CHECK_CONTRACT_INFO",
    "FETCH_CONTRACT_INFO",
    "READ_CONTRACT_INFO",
    "DISPLAY_CONTRACT_INFO",
    "SHOW_CONTRACT_INFO",
    "LIST_CONTRACT_INFO",
    "RETRIEVE_CONTRACT_INFO",
];

export const getContractHistorySimiles = [
    "VIEW_CONTRACT_HISTORY",
    "GET_CONTRACT_HISTORY",
    "CHECK_CONTRACT_HISTORY",
    "FETCH_CONTRACT_HISTORY",
    "READ_CONTRACT_HISTORY",
    "DISPLAY_CONTRACT_HISTORY",
    "SHOW_CONTRACT_HISTORY",
    "LIST_CONTRACT_HISTORY",
    "RETRIEVE_CONTRACT_HISTORY",
];

export const getSmartContractStateSimiles = [
    "VIEW_SMART_STATE",
    "GET_SMART_STATE",
    "CHECK_SMART_STATE",
    "FETCH_SMART_STATE",
    "READ_SMART_STATE",
    "DISPLAY_SMART_STATE",
    "SHOW_SMART_STATE",
    "LIST_SMART_STATE",
    "RETRIEVE_SMART_STATE",
];

export const getRawContractStateSimiles = [
    "VIEW_RAW_STATE",
    "GET_RAW_STATE",
    "CHECK_RAW_STATE",
    "FETCH_RAW_STATE",
    "READ_RAW_STATE",
    "DISPLAY_RAW_STATE",
    "SHOW_RAW_STATE",
    "LIST_RAW_STATE",
    "RETRIEVE_RAW_STATE",
];

// Code Query Actions
export const getContractCodesSimiles = [
    "VIEW_CONTRACT_CODES",
    "GET_CONTRACT_CODES",
    "CHECK_CONTRACT_CODES",
    "FETCH_CONTRACT_CODES",
    "READ_CONTRACT_CODES",
    "DISPLAY_CONTRACT_CODES",
    "SHOW_CONTRACT_CODES",
    "LIST_CONTRACT_CODES",
    "RETRIEVE_CONTRACT_CODES",
];

export const getContractCodeSimiles = [
    "VIEW_CONTRACT_CODE",
    "GET_CONTRACT_CODE",
    "CHECK_CONTRACT_CODE",
    "FETCH_CONTRACT_CODE",
    "READ_CONTRACT_CODE",
    "DISPLAY_CONTRACT_CODE",
    "SHOW_CONTRACT_CODE",
    "LIST_CONTRACT_CODE",
    "RETRIEVE_CONTRACT_CODE",
];

export const getContractCodeContractsSimiles = [
    "VIEW_CODE_CONTRACTS",
    "GET_CODE_CONTRACTS",
    "CHECK_CODE_CONTRACTS",
    "FETCH_CODE_CONTRACTS",
    "READ_CODE_CONTRACTS",
    "DISPLAY_CODE_CONTRACTS",
    "SHOW_CODE_CONTRACTS",
    "LIST_CODE_CONTRACTS",
    "RETRIEVE_CODE_CONTRACTS",
];

// Message Actions
export const msgStoreCodeSimiles = [
    "STORE_CONTRACT_CODE",
    "UPLOAD_CONTRACT_CODE",
    "DEPLOY_CONTRACT_CODE",
    "SUBMIT_CONTRACT_CODE",
    "PUBLISH_CONTRACT_CODE",
    "REGISTER_CONTRACT_CODE",
    "SAVE_CONTRACT_CODE",
    "INSTALL_CONTRACT_CODE",
    "PUSH_CONTRACT_CODE",
];

export const msgUpdateAdminSimiles = [
    "UPDATE_CONTRACT_ADMIN",
    "CHANGE_CONTRACT_ADMIN",
    "MODIFY_CONTRACT_ADMIN",
    "TRANSFER_CONTRACT_ADMIN",
    "REPLACE_CONTRACT_ADMIN",
    "REASSIGN_CONTRACT_ADMIN",
    "SWITCH_CONTRACT_ADMIN",
    "ALTER_CONTRACT_ADMIN",
    "REVISE_CONTRACT_ADMIN",
];

export const msgExecuteContractSimiles = [
    "EXECUTE_CONTRACT",
    "RUN_CONTRACT",
    "CALL_CONTRACT",
    "INVOKE_CONTRACT",
    "TRIGGER_CONTRACT",
    "PERFORM_CONTRACT",
    "PROCESS_CONTRACT",
    "START_CONTRACT",
    "OPERATE_CONTRACT",
];

export const msgMigrateContractSimiles = [
    "MIGRATE_CONTRACT",
    "UPGRADE_CONTRACT",
    "UPDATE_CONTRACT",
    "TRANSFER_CONTRACT",
    "MOVE_CONTRACT",
    "SHIFT_CONTRACT",
    "PORT_CONTRACT",
    "TRANSITION_CONTRACT",
    "CONVERT_CONTRACT",
];

export const msgInstantiateContractSimiles = [
    "CREATE_CONTRACT_INSTANCE",
    "INSTANTIATE_CONTRACT",
    "INITIALIZE_CONTRACT",
    "DEPLOY_CONTRACT",
    "LAUNCH_CONTRACT",
    "START_CONTRACT_INSTANCE",
    "SETUP_CONTRACT",
    "ESTABLISH_CONTRACT",
    "GENERATE_CONTRACT",
];

export const msgExecuteContractCompatSimiles = [
    "EXECUTE_COMPAT_CONTRACT",
    "RUN_COMPAT_CONTRACT",
    "CALL_COMPAT_CONTRACT",
    "INVOKE_COMPAT_CONTRACT",
    "TRIGGER_COMPAT_CONTRACT",
    "PERFORM_COMPAT_CONTRACT",
    "PROCESS_COMPAT_CONTRACT",
    "START_COMPAT_CONTRACT",
    "OPERATE_COMPAT_CONTRACT",
];

export const msgPrivilegedExecuteContractSimiles = [
    "EXECUTE_PRIVILEGED_CONTRACT",
    "RUN_PRIVILEGED_CONTRACT",
    "CALL_PRIVILEGED_CONTRACT",
    "INVOKE_PRIVILEGED_CONTRACT",
    "TRIGGER_PRIVILEGED_CONTRACT",
    "PERFORM_PRIVILEGED_CONTRACT",
    "PROCESS_PRIVILEGED_CONTRACT",
    "START_PRIVILEGED_CONTRACT",
    "OPERATE_PRIVILEGED_CONTRACT",
];

// WasmX Query Actions
export const getWasmxModuleParamsSimiles = [
    "VIEW_WASMX_PARAMS",
    "GET_WASMX_PARAMS",
    "CHECK_WASMX_PARAMS",
    "FETCH_WASMX_PARAMS",
    "READ_WASMX_PARAMS",
    "DISPLAY_WASMX_PARAMS",
    "SHOW_WASMX_PARAMS",
    "LIST_WASMX_PARAMS",
    "RETRIEVE_WASMX_PARAMS",
];

export const getWasmxModuleStateSimiles = [
    "VIEW_WASMX_STATE",
    "GET_WASMX_STATE",
    "CHECK_WASMX_STATE",
    "FETCH_WASMX_STATE",
    "READ_WASMX_STATE",
    "DISPLAY_WASMX_STATE",
    "SHOW_WASMX_STATE",
    "LIST_WASMX_STATE",
    "RETRIEVE_WASMX_STATE",
];
