import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Home',
    },
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 Introduction',
    },
    {
      type: 'category',
      label: '🏁 Getting Started',
      items: [
        {
          type: 'doc',
          id: 'quickstart',
          label: '⭐ Quick Start',
        },
        {
          type: 'doc',
          id: 'faq',
          label: '❓ FAQ',
        },
        {
          type: 'doc',
          id: 'contributing',
          label: '👥 Contributing',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '🧠 Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'core/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'core/actions',
          label: 'Actions',
        },
        {
          type: 'doc',
          id: 'core/agents',
          label: 'Agent Runtime',
        },
        {
          type: 'doc',
          id: 'core/database',
          label: 'Database Adapters',
        },
        {
          type: 'doc',
          id: 'core/entities',
          label: 'Entities',
        },
        {
          type: 'doc',
          id: 'core/evaluators',
          label: 'Evaluators',
        },
        {
          type: 'doc',
          id: 'core/characters',
          label: 'Character Files',
        },
        {
          type: 'doc',
          id: 'core/knowledge',
          label: 'Knowledge',
        },
        {
          type: 'doc',
          id: 'core/plugins',
          label: 'Plugins',
        },
        {
          type: 'doc',
          id: 'core/project',
          label: 'Project',
        },
        {
          type: 'doc',
          id: 'core/providers',
          label: 'Providers',
        },
        {
          type: 'doc',
          id: 'core/rooms',
          label: 'Rooms',
        },
        {
          type: 'doc',
          id: 'core/services',
          label: 'Services',
        },
        {
          type: 'doc',
          id: 'core/tasks',
          label: 'Tasks',
        },
        {
          type: 'doc',
          id: 'core/worlds',
          label: 'Worlds',
        },
        {
          type: 'doc',
          id: 'core/testing',
          label: 'Testing',
        },
      ],
    },
    {
      type: 'category',
      label: '🖥️ CLI',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'cli/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'cli/agent',
          label: 'Agent',
        },
        {
          type: 'doc',
          id: 'cli/create',
          label: 'Create',
        },
        {
          type: 'doc',
          id: 'cli/dev',
          label: 'Dev',
        },
        {
          type: 'doc',
          id: 'cli/env',
          label: 'Environment',
        },
        // {
        //   type: 'doc',
        //   id: 'cli/plugins',
        //   label: 'Plugins',
        // },
        // {
        //   type: 'doc',
        //   id: 'cli/projects',
        //   label: 'Projects',
        // },
        {
          type: 'doc',
          id: 'cli/publish',
          label: 'Publish',
        },
        {
          type: 'doc',
          id: 'cli/start',
          label: 'Start',
        },
        {
          type: 'doc',
          id: 'cli/test',
          label: 'Test',
        },
        {
          type: 'doc',
          id: 'cli/update',
          label: 'Update',
        },
      ],
    },
    {
      type: 'category',
      label: '🌐 REST API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'rest',
        },
      ],
      collapsed: true,
    },
    {
      type: 'doc',
      id: 'awesome-eliza',
      label: 'Awesome elizaOS',
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'CHANGELOG',
    },
  ],
  
  // Simple track for non-technical users
  simpleSidebar: [
    {
      type: 'category',
      label: '🎯 Getting Started',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'simple/getting-started/quick-start',
          label: '⚡ 5-Minute Quick Start',
        },
        {
          type: 'doc',
          id: 'simple/getting-started/first-agent',
          label: '🤖 Your First Agent',
        },
        {
          type: 'doc',
          id: 'simple/getting-started/troubleshooting',
          label: '🔧 Troubleshooting',
        },
      ],
    },
    {
      type: 'category',
      label: '🎨 Templates & Examples',
      items: [
        {
          type: 'doc',
          id: 'simple/templates/gallery',
          label: '📚 Template Gallery',
        },
        {
          type: 'doc',
          id: 'simple/templates/customization',
          label: '✏️ Customization Guide',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 Guides',
      items: [
        {
          type: 'doc',
          id: 'simple/guides/character-creation',
          label: '👤 Character Creation',
        },
        {
          type: 'doc',
          id: 'simple/guides/plugin-usage',
          label: '🧩 Using Plugins',
        },
        {
          type: 'doc',
          id: 'simple/guides/deployment',
          label: '🚀 Deployment',
        },
      ],
    },
    {
      type: 'doc',
      id: 'simple/faq',
      label: '❓ FAQ',
    },
  ],

  // Technical track for developers
  technicalSidebar: [
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'technical/architecture/overview',
          label: '📐 System Overview',
        },
        {
          type: 'doc',
          id: 'technical/architecture/core-concepts',
          label: '🧠 Core Concepts',
        },
        {
          type: 'doc',
          id: 'technical/architecture/state-management',
          label: '💾 State Management',
        },
        {
          type: 'doc',
          id: 'technical/architecture/plugin-system',
          label: '🔌 Plugin Architecture',
        },
      ],
    },
    {
      type: 'category',
      label: '💻 Development',
      items: [
        {
          type: 'doc',
          id: 'technical/development/monorepo-guide',
          label: '📦 Monorepo Development',
        },
        {
          type: 'doc',
          id: 'technical/development/standalone-guide',
          label: '🚀 Standalone Projects',
        },
        {
          type: 'doc',
          id: 'technical/development/plugin-development',
          label: '🔧 Plugin Development',
        },
        {
          type: 'doc',
          id: 'technical/development/testing-guide',
          label: '🧪 Testing Guide',
        },
      ],
    },
    {
      type: 'category',
      label: '📚 API Reference',
      items: [
        {
          type: 'doc',
          id: 'technical/api-reference/core-api',
          label: '🔵 Core API',
        },
        {
          type: 'doc',
          id: 'technical/api-reference/plugin-api',
          label: '🧩 Plugin API',
        },
        {
          type: 'doc',
          id: 'technical/api-reference/service-api',
          label: '⚙️ Service API',
        },
      ],
    },
    {
      type: 'category',
      label: '🚀 Advanced Topics',
      items: [
        {
          type: 'doc',
          id: 'technical/advanced/performance',
          label: '⚡ Performance',
        },
        {
          type: 'doc',
          id: 'technical/advanced/scaling',
          label: '📈 Scaling',
        },
        {
          type: 'doc',
          id: 'technical/advanced/security',
          label: '🔐 Security',
        },
      ],
    },
    {
      type: 'doc',
      id: 'technical/faq',
      label: '❓ Technical FAQ',
    },
  ],
};

export default sidebars;
