import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: '🏠 Home',
    },
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 Introduction',
    },
    {
      type: 'category',
      label: '🏁 Getting Started',
      items: [
        {
          type: 'doc',
          id: 'quickstart',
          label: '⭐ Quick Start',
        },
        {
          type: 'doc',
          id: 'faq',
          label: '❓ FAQ',
        },
        {
          type: 'doc',
          id: 'contributing',
          label: '👥 Contributing',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: '🧠 Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'core/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'core/actions',
          label: 'Actions',
        },
        {
          type: 'doc',
          id: 'core/agents',
          label: 'Agent Runtime',
        },
        {
          type: 'doc',
          id: 'core/database',
          label: 'Database Adapters',
        },
        {
          type: 'doc',
          id: 'core/entities',
          label: 'Entities',
        },
        {
          type: 'doc',
          id: 'core/evaluators',
          label: 'Evaluators',
        },
        {
          type: 'doc',
          id: 'core/characters',
          label: 'Character Files',
        },
        {
          type: 'doc',
          id: 'core/knowledge',
          label: 'Knowledge',
        },
        {
          type: 'doc',
          id: 'core/plugins',
          label: 'Plugins',
        },
        {
          type: 'doc',
          id: 'core/project',
          label: 'Project',
        },
        {
          type: 'doc',
          id: 'core/providers',
          label: 'Providers',
        },
        {
          type: 'doc',
          id: 'core/rooms',
          label: 'Rooms',
        },
        {
          type: 'doc',
          id: 'core/services',
          label: 'Services',
        },
        {
          type: 'doc',
          id: 'core/tasks',
          label: 'Tasks',
        },
        {
          type: 'doc',
          id: 'core/worlds',
          label: 'Worlds',
        },
        {
          type: 'doc',
          id: 'core/testing',
          label: 'Testing',
        },
      ],
    },
    {
      type: 'category',
      label: '🖥️ CLI',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'cli/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'cli/agent',
          label: 'Agent',
        },
        {
          type: 'doc',
          id: 'cli/create',
          label: 'Create',
        },
        {
          type: 'doc',
          id: 'cli/dev',
          label: 'Dev',
        },
        {
          type: 'doc',
          id: 'cli/env',
          label: 'Environment',
        },
        // {
        //   type: 'doc',
        //   id: 'cli/plugins',
        //   label: 'Plugins',
        // },
        // {
        //   type: 'doc',
        //   id: 'cli/projects',
        //   label: 'Projects',
        // },
        {
          type: 'doc',
          id: 'cli/publish',
          label: 'Publish',
        },
        {
          type: 'doc',
          id: 'cli/start',
          label: 'Start',
        },
        {
          type: 'doc',
          id: 'cli/test',
          label: 'Test',
        },
        {
          type: 'doc',
          id: 'cli/update',
          label: 'Update',
        },
      ],
    },
    {
      type: 'category',
      label: '🌐 REST API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'rest',
        },
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🎨 Design System',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'design-system/index',
          label: '🎭 Overview',
        },
        {
          type: 'doc',
          id: 'design-system/components',
          label: '🧩 Components',
        },
        {
          type: 'doc',
          id: 'design-system/animations',
          label: '🎞️ Animations',
        },
        {
          type: 'doc',
          id: 'design-system/performance',
          label: '⚡ Performance',
        },
        {
          type: 'doc',
          id: 'design-system/accessibility',
          label: '♿ Accessibility',
        },
        {
          type: 'doc',
          id: 'design-system/implementation',
          label: '🚀 Implementation',
        },
      ],
    },
    {
      type: 'doc',
      id: 'awesome-eliza',
      label: 'Awesome elizaOS',
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'CHANGELOG',
    },
  ],

  // Simple track for non-technical users
  simpleSidebar: [
    {
      type: 'category',
      label: '🎯 Getting Started',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'simple/getting-started/quick-start',
          label: '⚡ 5-Minute Quick Start',
        },
      ],
    },
    {
      type: 'category',
      label: '🎨 Templates & Examples',
      items: [
        {
          type: 'doc',
          id: 'simple/templates/gallery',
          label: '📚 Template Gallery',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 Guides',
      items: [
        {
          type: 'doc',
          id: 'simple/guides/character-creation',
          label: '👤 Character Creation',
        },
        {
          type: 'doc',
          id: 'simple/guides/cli-setup',
          label: '🔧 CLI Setup',
        },
        {
          type: 'doc',
          id: 'simple/guides/discord-setup',
          label: '🎮 Discord Setup',
        },
        {
          type: 'doc',
          id: 'simple/guides/telegram-setup',
          label: '📱 Telegram Setup',
        },
        {
          type: 'doc',
          id: 'simple/guides/twitter-setup',
          label: '🐦 Twitter Setup',
        },
      ],
    },
    {
      type: 'doc',
      id: 'simple/faq',
      label: '❓ FAQ',
    },
  ],

  // Technical track for developers
  technicalSidebar: [
    {
      type: 'category',
      label: '🏗️ Architecture',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'technical/architecture/overview',
          label: '📐 System Overview',
        },
        {
          type: 'doc',
          id: 'technical/architecture/core-concepts',
          label: '🧠 Core Concepts',
        },
        {
          type: 'doc',
          id: 'technical/architecture/state-management',
          label: '💾 State Management',
        },
      ],
    },
    {
      type: 'category',
      label: '📚 API Reference',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'technical/api-reference/actions-api',
          label: '⚡ Actions API',
        },
      ],
    },
    {
      type: 'category',
      label: '🔗 Platform Integrations',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'technical/integrations/twitter-technical',
          label: '🐦 Twitter Technical Integration',
        },
      ],
    },
    {
      type: 'doc',
      id: 'technical/faq',
      label: '❓ Technical FAQ',
    },
  ],

  // Customize track for power users who want to personalize their agents
  customizeSidebar: [
    {
      type: 'doc',
      id: 'customize/overview',
      label: '🎨 Customize Overview',
    },
    {
      type: 'category',
      label: '🎯 Interactive Tools',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'customize/character-builder',
          label: '👤 Character Builder',
        },
        {
          type: 'doc',
          id: 'customize/environment-builder',
          label: '🌍 Environment Builder',
        },
        {
          type: 'doc',
          id: 'customize/visual-lab',
          label: '🎨 Visual Lab',
        },
        {
          type: 'doc',
          id: 'customize/feature-workshop',
          label: '🔧 Feature Workshop',
        },
        {
          type: 'doc',
          id: 'customize/analytics',
          label: '📊 Analytics Dashboard',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Platform Configuration',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'customize/twitter-advanced',
          label: '🐦 Twitter Advanced Setup',
        },
      ],
    },
  ],
};

export default sidebars;
