import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'specs/v1/index': 'src/specs/v1/index.ts',
    'specs/v2/index': 'src/specs/v2/index.ts',
  },
  outDir: 'dist',
  clean: true,
  format: ['esm'],
  target: 'node18',
  dts: true,
  external: [
    'dotenv',
    'fs',
    'path',
    'node:fs',
    'node:path',
    'node:crypto',
    'node:web',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'node:http',
    'node:https',
    'http',
    'https',
    'sharp',
    '@solana/web3.js',
    'zod',
    '@hapi/shot',
    '@opentelemetry/api',
    '@opentelemetry/context-async-hooks',
    '@opentelemetry/sdk-trace-node',
  ],
  sourcemap: false,
});
