import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/specs/v1/index.ts',
    'src/specs/v1/state.ts',
    'src/specs/v1/actionExample.ts',
    'src/specs/v1/templates.ts',
    'src/specs/v1/uuid.ts',
    'src/specs/v1/provider.ts',
    'src/specs/v1/messages.ts',
    'src/specs/v1/posts.ts',
    'src/specs/v1/runtime.ts',
    'src/specs/v1/types.ts',
    'src/specs/v2/index.ts',
  ],
  outDir: 'dist',
  clean: true,
  format: ['esm'],
  target: 'node18',
  dts: true,
  tsconfig: './tsconfig.build.json', // Use build-specific tsconfig
  ignoreWatch: ['**/__tests__/**', '**/test_resources/**'],
  external: [
    'dotenv',
    'fs',
    'path',
    'node:fs',
    'node:path',
    'node:crypto',
    'node:web',
    'node:stream',
    'node:buffer',
    'node:util',
    'node:events',
    'node:url',
    'node:http',
    'node:https',
    'http',
    'https',
    'sharp',
    '@solana/web3.js',
    'zod',
    '@hapi/shot',
    '@opentelemetry/api',
    '@opentelemetry/context-async-hooks',
    '@opentelemetry/sdk-trace-node',
  ],
  sourcemap: false,
});
